import type { LiveInsightContext, InsightTrigger } from "@/lib/mlb/nerdInsights/types";

export type InsightTeamSide = "offense" | "defense";
export type InsightPolarity = "elite" | "cursed" | "either";

export interface EventInsightSpec {
  statId: string;
  team: InsightTeamSide;
  polarity: InsightPolarity;
  triggerTypes: InsightTrigger["type"][];
  eliteMaxRank?: number;
  cursedBottomN?: number;
  /** Hand-crafted rules take priority when their statId matches. */
  skipIfHandCrafted?: boolean;
  match?: (ctx: LiveInsightContext) => boolean;
  eventEquals?: string[];
  eventIncludes?: string[];
  eyebrow: string;
  title: (ctx: LiveInsightContext, abbrev: string) => string;
  message: (
    ctx: LiveInsightContext,
    abbrev: string,
    statTitle: string,
    displayValue: string,
    rank: number,
  ) => string;
}

function offenseRuns(ctx: LiveInsightContext): number {
  return ctx.offenseTeamId === ctx.awayTeamId ? ctx.awayRuns : ctx.homeRuns;
}

function defenseRunsAllowed(ctx: LiveInsightContext): number {
  return ctx.defenseTeamId === ctx.awayTeamId ? ctx.awayRuns : ctx.homeRuns;
}

function totalRuns(ctx: LiveInsightContext): number {
  return ctx.awayRuns + ctx.homeRuns;
}

function runsInHalf(ctx: LiveInsightContext): number | null {
  if (ctx.trigger.type !== "half-break") return null;
  return ctx.liveStats?.runsByHalf[ctx.trigger.halfKey] ?? null;
}

function defaultMessage(
  _ctx: LiveInsightContext,
  abbrev: string,
  statTitle: string,
  displayValue: string,
  rank: number,
): string {
  return `${abbrev} rank #${rank} in ${statTitle.toLowerCase()} (${displayValue}).`;
}

/** Stat IDs already covered by hand-tuned situational rules in generate.ts. */
export const HAND_CRAFTED_INSIGHT_STAT_IDS = new Set([
  "pitches-seen-per-half",
  "quick-half-innings-seen",
  "long-half-innings-seen",
  "long-half-innings-thrown",
  "longest-half-inning-pitches",
  "foul-ball-factory",
  "runs-scored",
  "runs-allowed",
  "runs-per-game",
  "risp-batting",
  "runs-with-two-outs-pct",
  "bases-loaded-no-runs",
  "pitches-per-pa",
  "foul-rate",
  "ball-rate",
  "full-count-ops",
  "called-strike-rate",
  "swinging-strike-rate",
  "walks-per-game",
  "double-plays-hit-into",
  "walk-off-wins",
  "one-run-games",
  "extra-inning-win-pct",
  "blowout-wins",
  "run-differential",
  "pitches-thrown-per-half",
]);

function atBatEnd(
  spec: Omit<EventInsightSpec, "triggerTypes"> & {
    eventEquals?: string[];
    eventIncludes?: string[];
  },
): EventInsightSpec {
  return { ...spec, triggerTypes: ["at-bat-end"] };
}

function atBatStart(
  spec: Omit<EventInsightSpec, "triggerTypes">,
): EventInsightSpec {
  return { ...spec, triggerTypes: ["at-bat-start"] };
}

function halfBreak(
  spec: Omit<EventInsightSpec, "triggerTypes">,
): EventInsightSpec {
  return { ...spec, triggerTypes: ["half-break"] };
}

function inningChange(
  spec: Omit<EventInsightSpec, "triggerTypes">,
): EventInsightSpec {
  return { ...spec, triggerTypes: ["inning-change"] };
}

function pitchThrown(
  spec: Omit<EventInsightSpec, "triggerTypes">,
): EventInsightSpec {
  return { ...spec, triggerTypes: ["pitch-thrown"] };
}

export const EVENT_INSIGHT_SPECS: EventInsightSpec[] = [
  // —— At-bat results (offense) ——
  atBatEnd({
    statId: "strikeout-rate",
    team: "offense",
    polarity: "either",
    eventEquals: ["Strikeout"],
    eyebrow: "Whiff watch",
    title: () => "Another strikeout",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "contact-rate",
    team: "offense",
    polarity: "cursed",
    eventEquals: ["Strikeout"],
    eyebrow: "Contact crisis",
    title: (ctx, abbrev) => `${abbrev} can't put it in play`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "walk-rate",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Walk", "Intent Walk", "Intentional Walk"],
    eyebrow: "Free pass",
    title: () => "Take your base",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "intent-walk-rate",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Intent Walk", "Intentional Walk"],
    eyebrow: "Intentional traffic",
    title: () => "Pitch-around profile",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "hit-by-pitch",
    team: "offense",
    polarity: "either",
    eventEquals: ["Hit By Pitch"],
    eyebrow: "Plunked",
    title: (ctx) => `${ctx.batterName} takes one for the team`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "hbp-rate",
    team: "offense",
    polarity: "either",
    eventEquals: ["Hit By Pitch"],
    eyebrow: "Plunked",
    title: () => "Hit by pitch",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "hr-per-pa",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Home Run"],
    eyebrow: "Long ball",
    title: (ctx) => `${ctx.batterName} goes deep`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "moonshot-hrs",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Home Run"],
    eyebrow: "Moonshot merchants",
    title: () => "Tower shot",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "no-doubter-hr-rate",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Home Run"],
    eyebrow: "No doubter",
    title: () => "That one had a chance",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "grand-slams",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Home Run"],
    match: (ctx) => ctx.basesLoaded,
    eyebrow: "Bases juiced",
    title: () => "Grand slam territory",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "leadoff-homers",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Home Run"],
    match: (ctx) => ctx.outs === 0,
    eyebrow: "Leadoff pop",
    title: () => "Leadoff bomb",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "inside-the-park-hrs",
    team: "offense",
    polarity: "either",
    eventEquals: ["Home Run"],
    eyebrow: "Chaos baseball",
    title: () => "Rare air",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "wall-scraper-hrs",
    team: "offense",
    polarity: "either",
    eventEquals: ["Home Run"],
    eyebrow: "Wall scraper",
    title: () => "Just enough",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "bloop-singles",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Single"],
    eyebrow: "Bloop factory",
    title: () => "Another bleeder",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "infield-singles",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Single"],
    eyebrow: "Dust off the uniform",
    title: () => "Infield knock",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "doubles-factory",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Double"],
    eyebrow: "Gap power",
    title: () => "Extra bases",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "triples-helmet",
    team: "offense",
    polarity: "either",
    eventEquals: ["Triple"],
    eyebrow: "Wheels",
    title: () => "Three-bagger",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "extra-base-rate",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Double", "Triple", "Home Run"],
    eyebrow: "Extra bases",
    title: () => "Power surge",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "gidp-rate",
    team: "offense",
    polarity: "cursed",
    eventIncludes: ["Double Play"],
    eyebrow: "Rally killer",
    title: () => "Twin killing",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "rally-killer-gidp",
    team: "offense",
    polarity: "cursed",
    eventIncludes: ["Double Play"],
    match: (ctx) => ctx.runnersInScoringPosition,
    eyebrow: "Rally killer",
    title: () => "Scoring chance erased",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "sac-fly-rate",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Sac Fly"],
    eyebrow: "Small ball",
    title: () => "Sac fly",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "sac-bunt-society",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Sac Bunt", "Sacrifice Bunt"],
    eyebrow: "Small ball",
    title: () => "Sac bunt",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "small-ball-score",
    team: "offense",
    polarity: "elite",
    eventEquals: ["Sac Fly", "Sac Bunt", "Sacrifice Bunt"],
    eyebrow: "Small ball",
    title: () => "Manufacturing runs",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "reached-on-error",
    team: "offense",
    polarity: "either",
    eventIncludes: ["Error"],
    eyebrow: "Gift runner",
    title: () => "Reached on error",
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "three-true-outcomes-rate",
    team: "offense",
    polarity: "either",
    eventEquals: ["Strikeout", "Walk", "Intent Walk", "Intentional Walk", "Home Run"],
    eyebrow: "Three true outcomes",
    title: () => "TTO baseball",
    message: defaultMessage,
  }),

  // —— At-bat results (defense) ——
  atBatEnd({
    statId: "gidp-induced",
    team: "defense",
    polarity: "elite",
    eventIncludes: ["Double Play"],
    eyebrow: "Twin killing",
    title: (ctx, abbrev) => `${abbrev} turn two`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "pitching-k-per-game",
    team: "defense",
    polarity: "elite",
    eventEquals: ["Strikeout"],
    eyebrow: "Freeze frame",
    title: (ctx, abbrev) => `${abbrev} punchout`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "swinging-strikes-per-game",
    team: "defense",
    polarity: "elite",
    eventEquals: ["Strikeout"],
    match: (ctx) => ctx.strikeoutKind === "swinging",
    eyebrow: "Whiff factory",
    title: (ctx, abbrev) => `${abbrev} get the K`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "fouls-induced-per-game",
    team: "defense",
    polarity: "elite",
    eventEquals: ["Strikeout"],
    eyebrow: "Pitcher's duel",
    title: (ctx, abbrev) => `${abbrev} miss bats`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "errors-committed",
    team: "defense",
    polarity: "cursed",
    eventIncludes: ["Error"],
    eyebrow: "Defensive miscue",
    title: (ctx, abbrev) => `${abbrev} boot one`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "fielding-errors",
    team: "defense",
    polarity: "cursed",
    eventIncludes: ["Error"],
    eyebrow: "Defensive miscue",
    title: (ctx, abbrev) => `${abbrev} with the error`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "throwing-errors",
    team: "defense",
    polarity: "cursed",
    eventIncludes: ["Error"],
    eyebrow: "Throwing error",
    title: (ctx, abbrev) => `${abbrev} throw it away`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "multi-hr-games-allowed",
    team: "defense",
    polarity: "cursed",
    eventEquals: ["Home Run"],
    eyebrow: "Long ball allowed",
    title: (ctx, abbrev) => `${abbrev} serve one up`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "hardest-hit-allowed",
    team: "defense",
    polarity: "cursed",
    eventEquals: ["Home Run", "Double"],
    eyebrow: "Barreled up",
    title: (ctx, abbrev) => `${abbrev} get tagged`,
    message: defaultMessage,
  }),
  atBatEnd({
    statId: "immaculate-inning-victim",
    team: "offense",
    polarity: "cursed",
    eventEquals: ["Strikeout"],
    eyebrow: "Immaculate threat",
    title: () => "Nine-pitch nightmare fuel",
    message: defaultMessage,
  }),

  // —— At-bat start ——
  atBatStart({
    statId: "steal-attempt-rate",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.onFirst && !ctx.onSecond && !ctx.onThird,
    eyebrow: "Running game",
    title: (ctx, abbrev) => `${abbrev} might run`,
    message: defaultMessage,
  }),
  atBatStart({
    statId: "steal-success-rate",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.onFirst && !ctx.onSecond && !ctx.onThird,
    eyebrow: "Running game",
    title: (ctx, abbrev) => `${abbrev} speed threat`,
    message: defaultMessage,
  }),
  atBatStart({
    statId: "caught-stealing",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.onFirst && !ctx.onSecond && !ctx.onThird,
    eyebrow: "Running game",
    title: (ctx, abbrev) => `${abbrev} run into outs`,
    message: defaultMessage,
  }),
  atBatStart({
    statId: "pickoffs-suffered",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.onFirst,
    eyebrow: "Pickoff watch",
    title: (ctx, abbrev) => `${abbrev} leadoff woes`,
    message: defaultMessage,
  }),
  atBatStart({
    statId: "left-on-base",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.twoOuts && ctx.runnersInScoringPosition,
    eyebrow: "LOB watch",
    title: (ctx, abbrev) => `${abbrev} leave runners stranded`,
    message: defaultMessage,
  }),
  atBatStart({
    statId: "lob-nightmare-games",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.twoOuts && ctx.runnersInScoringPosition,
    eyebrow: "LOB nightmare",
    title: (ctx, abbrev) => `${abbrev} strand city`,
    message: defaultMessage,
  }),

  // —— Pitch milestones ——
  pitchThrown({
    statId: "full-count-obp",
    team: "offense",
    polarity: "elite",
    match: (ctx) =>
      ctx.trigger.type === "pitch-thrown" &&
      ctx.balls === 3 &&
      ctx.strikes === 2,
    eyebrow: "3-2 chess match",
    title: () => "Full count standoff",
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "full-count-slg",
    team: "offense",
    polarity: "elite",
    match: (ctx) =>
      ctx.trigger.type === "pitch-thrown" &&
      ctx.balls === 3 &&
      ctx.strikes === 2,
    eyebrow: "3-2 chess match",
    title: () => "Full count power",
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "pitch-bip-rate",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 5,
    eyebrow: "Contact watch",
    title: () => "Battle at the plate",
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "pitches-per-hit",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 6,
    eyebrow: "Marathon at-bat",
    title: () => "Working the count",
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "pitches-per-run",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 7,
    eyebrow: "Run manufacturing",
    title: () => "Grinding for runs",
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "pitches-per-hit-allowed",
    team: "defense",
    polarity: "elite",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 6,
    eyebrow: "Pitcher's duel",
    title: (ctx, abbrev) => `${abbrev} making them work`,
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "pitches-per-run-allowed",
    team: "defense",
    polarity: "elite",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 7,
    eyebrow: "Run prevention",
    title: (ctx, abbrev) => `${abbrev} staff efficiency`,
    message: defaultMessage,
  }),
  pitchThrown({
    statId: "balls-in-play-allowed-rate",
    team: "defense",
    polarity: "either",
    match: (ctx) => ctx.trigger.type === "pitch-thrown" && ctx.trigger.pitchNumber >= 5,
    eyebrow: "Contact allowed",
    title: (ctx, abbrev) => `${abbrev} in the zone`,
    message: defaultMessage,
  }),

  // —— Half-inning breaks ——
  halfBreak({
    statId: "first-inning-runs",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.inning === 1 && (runsInHalf(ctx) ?? 0) >= 1,
    eyebrow: "First-inning ambush",
    title: (ctx, abbrev) => `${abbrev} strike first`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "first-inning-run-share",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.inning === 1 && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "First-inning ambush",
    title: (ctx, abbrev) => `${abbrev} open hot`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "late-inning-runs",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.isLateInning && (runsInHalf(ctx) ?? 0) >= 1,
    eyebrow: "Late-inning panic",
    title: (ctx, abbrev) => `${abbrev} strike late`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "late-inning-run-share",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.isLateInning && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "Late-inning panic",
    title: (ctx, abbrev) => `${abbrev} clutch frame`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "first-inning-runs-allowed",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.inning === 1 && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "First-inning leak",
    title: (ctx, abbrev) => `${abbrev} stumble early`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "first-inning-runs-allowed-share",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.inning === 1 && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "First-inning leak",
    title: (ctx, abbrev) => `${abbrev} open cold`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "late-inning-runs-allowed",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.isLateInning && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "Late-inning leak",
    title: (ctx, abbrev) => `${abbrev} bleed late`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "late-inning-runs-allowed-share",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.isLateInning && (runsInHalf(ctx) ?? 0) >= 2,
    eyebrow: "Late-inning leak",
    title: (ctx, abbrev) => `${abbrev} fold late`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "runs-allowed-per-game",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => (runsInHalf(ctx) ?? 0) >= 3,
    eyebrow: "Runs allowed watch",
    title: (ctx, abbrev) => `${abbrev} give up a crooked number`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "quick-half-innings-thrown",
    team: "defense",
    polarity: "elite",
    match: (ctx) => {
      if (ctx.trigger.type !== "half-break") return false;
      const pitches = ctx.liveStats?.pitchesByHalf[ctx.trigger.halfKey];
      return pitches != null && pitches < 10;
    },
    eyebrow: "Quick half",
    title: (ctx, abbrev) => `${abbrev} breeze through`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "shortest-half-inning-pitches",
    team: "offense",
    polarity: "elite",
    match: (ctx) => {
      if (ctx.trigger.type !== "half-break") return false;
      const pitches = ctx.liveStats?.pitchesByHalf[ctx.trigger.halfKey];
      return pitches != null && pitches < 10;
    },
    eyebrow: "Quick half",
    title: (ctx, abbrev) => `${abbrev} speed through`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "shortest-half-inning-pitches-thrown",
    team: "defense",
    polarity: "elite",
    match: (ctx) => {
      if (ctx.trigger.type !== "half-break") return false;
      const pitches = ctx.liveStats?.pitchesByHalf[ctx.trigger.halfKey];
      return pitches != null && pitches < 10;
    },
    eyebrow: "Quick half",
    title: (ctx, abbrev) => `${abbrev} efficient frame`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "error-free-rate",
    team: "defense",
    polarity: "elite",
    match: (ctx) => (runsInHalf(ctx) ?? 0) === 0,
    eyebrow: "Clean defense",
    title: (ctx, abbrev) => `${abbrev} spotless half`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "error-free-games",
    team: "defense",
    polarity: "elite",
    match: (ctx) => (runsInHalf(ctx) ?? 0) === 0,
    eyebrow: "Clean defense",
    title: (ctx, abbrev) => `${abbrev} error-free track`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "zero-walk-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => (runsInHalf(ctx) ?? 0) === 0 && ctx.outs === 0,
    eyebrow: "Free-swinging",
    title: (ctx, abbrev) => `${abbrev} aggressive half`,
    message: defaultMessage,
  }),
  halfBreak({
    statId: "walkless-offense-rate",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => (runsInHalf(ctx) ?? 0) === 0,
    eyebrow: "Free-swinging",
    title: (ctx, abbrev) => `${abbrev} won't take a walk`,
    message: defaultMessage,
  }),

  // —— Inning changes ——
  inningChange({
    statId: "win-percentage",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.leadingTeamId === ctx.offenseTeamId && ctx.runMargin >= 3,
    eyebrow: "Traditional stat check",
    title: (ctx, abbrev) => `${abbrev} in control`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "runs-allowed-per-game",
    team: "defense",
    polarity: "elite",
    match: (ctx) => defenseRunsAllowed(ctx) === 0 && ctx.inning >= 3,
    eyebrow: "Shutout watch",
    title: (ctx, abbrev) => `${abbrev} blanking them`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "shutout-victim",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => offenseRuns(ctx) === 0 && ctx.inning >= 4,
    eyebrow: "Shutout watch",
    title: (ctx, abbrev) => `${abbrev} can't buy a run`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "pitcher-duel-games",
    team: "offense",
    polarity: "elite",
    match: (ctx) => totalRuns(ctx) <= 2 && ctx.inning >= 4,
    eyebrow: "Pitcher's duel",
    title: () => "Runs are scarce",
    message: defaultMessage,
  }),
  inningChange({
    statId: "whiff-fest-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) <= 2 && ctx.inning >= 5,
    eyebrow: "Whiff fest",
    title: () => "Strikeout derby vibes",
    message: defaultMessage,
  }),
  inningChange({
    statId: "eight-plus-run-games",
    team: "offense",
    polarity: "elite",
    match: (ctx) => totalRuns(ctx) >= 8,
    eyebrow: "Slugfest",
    title: () => "Runs are flying",
    message: defaultMessage,
  }),
  inningChange({
    statId: "ten-run-outbursts",
    team: "offense",
    polarity: "elite",
    match: (ctx) => totalRuns(ctx) >= 10,
    eyebrow: "Slugfest",
    title: () => "Double-digit scoring",
    message: defaultMessage,
  }),
  inningChange({
    statId: "comeback-wins",
    team: "offense",
    polarity: "elite",
    match: (ctx) =>
      ctx.trailingTeamId != null &&
      ctx.runMargin >= 3 &&
      ctx.isLateInning,
    eyebrow: "Comeback watch",
    title: (ctx, abbrev) => `${abbrev} still chasing`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "blowout-losses",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.runMargin >= 5 && ctx.trailingTeamId != null,
    eyebrow: "Blowout alert",
    title: (ctx, abbrev) => `${abbrev} getting routed`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "one-run-win-pct",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.isOneRunGame,
    eyebrow: "Nailbiter nation",
    title: () => "One-run game",
    message: defaultMessage,
  }),
  inningChange({
    statId: "one-run-losses",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.isOneRunGame && ctx.trailingTeamId != null,
    eyebrow: "Nailbiter nation",
    title: (ctx, abbrev) => `${abbrev} in another coin flip`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "extra-inning-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.isExtraInnings,
    eyebrow: "Bonus baseball",
    title: () => "Free baseball",
    message: defaultMessage,
  }),
  inningChange({
    statId: "extra-inning-losses",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.isExtraInnings && ctx.trailingTeamId != null,
    eyebrow: "Bonus baseball",
    title: (ctx, abbrev) => `${abbrev} extras heartbreak`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "walk-off-losses",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.isLateInning && ctx.isCloseGame && ctx.trailingTeamId != null,
    eyebrow: "Walk-off threat",
    title: (ctx, abbrev) => `${abbrev} walk-off victims`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "walkoff-bloop-singles",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.isLateInning && ctx.isCloseGame,
    eyebrow: "Walk-off weather",
    title: () => "Chaos ending possible",
    message: defaultMessage,
  }),
  inningChange({
    statId: "misfortune-index",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.trailingTeamId != null && ctx.runMargin >= 4,
    eyebrow: "Misfortune meter",
    title: (ctx, abbrev) => `${abbrev} misery mounting`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "chaos-luck-index",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.leadingTeamId != null && ctx.runMargin >= 4,
    eyebrow: "Chaos luck",
    title: (ctx, abbrev) => `${abbrev} riding the chaos`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "chaos-gift-runs-per-game",
    team: "offense",
    polarity: "elite",
    match: (ctx) => totalRuns(ctx) >= 6,
    eyebrow: "Chaos runs",
    title: () => "Gift runs weather",
    message: defaultMessage,
  }),
  inningChange({
    statId: "balk-beneficiaries",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.runnersInScoringPosition,
    eyebrow: "Chaos baseball",
    title: () => "Balk watch",
    message: defaultMessage,
  }),
  inningChange({
    statId: "wild-pitch-runs",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.onThird,
    eyebrow: "Wild pitch watch",
    title: () => "Dirt ball danger",
    message: defaultMessage,
  }),
  inningChange({
    statId: "passed-ball-runs",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.onThird,
    eyebrow: "Passed ball watch",
    title: () => "Ball in the dirt",
    message: defaultMessage,
  }),
  inningChange({
    statId: "error-assisted-runs",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.runnersInScoringPosition,
    eyebrow: "Error watch",
    title: () => "Defense could gift a run",
    message: defaultMessage,
  }),
  inningChange({
    statId: "error-runs-allowed",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.runnersInScoringPosition,
    eyebrow: "Error watch",
    title: (ctx, abbrev) => `${abbrev} error-prone`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "lob-per-game",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.runnersInScoringPosition && ctx.twoOuts,
    eyebrow: "LOB watch",
    title: (ctx, abbrev) => `${abbrev} strand runners`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "two-or-fewer-run-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => offenseRuns(ctx) <= 2 && ctx.inning >= 6,
    eyebrow: "Offensive drought",
    title: (ctx, abbrev) => `${abbrev} quiet bats`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "golden-sombrero",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.inning >= 6,
    eyebrow: "Sombrero watch",
    title: () => "Four-strikeout game lurking",
    message: defaultMessage,
  }),
  inningChange({
    statId: "blowout-win-share",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.runMargin >= 5 && ctx.leadingTeamId != null,
    eyebrow: "Blowout alert",
    title: (ctx, abbrev) => `${abbrev} run it up`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "total-pitches-seen",
    team: "offense",
    polarity: "elite",
    match: (ctx) => (ctx.liveStats?.totalPitches ?? 0) >= 120,
    eyebrow: "Pace check",
    title: () => "Marathon game",
    message: defaultMessage,
  }),
  inningChange({
    statId: "pinch-hit-success-rate",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.isLateInning,
    eyebrow: "Pinch-hit watch",
    title: () => "Bench weapon incoming?",
    message: defaultMessage,
  }),
  inningChange({
    statId: "pinch-hit-hits",
    team: "offense",
    polarity: "elite",
    match: (ctx) => ctx.isLateInning,
    eyebrow: "Pinch-hit watch",
    title: () => "Pinch-hit merchants",
    message: defaultMessage,
  }),
  inningChange({
    statId: "pinch-hit-chaos",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.isLateInning,
    eyebrow: "Pinch-hit chaos",
    title: () => "Chaos off the bench",
    message: defaultMessage,
  }),
  inningChange({
    statId: "pinch-hit-homer-rate",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.isLateInning && ctx.isCloseGame,
    eyebrow: "Pinch-hit power",
    title: () => "Pinch-hit bomb watch",
    message: defaultMessage,
  }),
  inningChange({
    statId: "no-hitter-bid-ruined",
    team: "defense",
    polarity: "either",
    match: (ctx) => defenseRunsAllowed(ctx) === 0 && ctx.inning >= 6,
    eyebrow: "No-hitter watch",
    title: (ctx, abbrev) => `${abbrev} bid still alive`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "errors-per-game",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.inning >= 4,
    eyebrow: "Error watch",
    title: (ctx, abbrev) => `${abbrev} sloppy track record`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "error-games",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.inning >= 4,
    eyebrow: "Error watch",
    title: (ctx, abbrev) => `${abbrev} error-prone season`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "multi-error-games",
    team: "defense",
    polarity: "cursed",
    match: (ctx) => ctx.inning >= 4,
    eyebrow: "Error watch",
    title: (ctx, abbrev) => `${abbrev} multi-error merchants`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "baserunning-blunders",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.onFirst || ctx.onSecond,
    eyebrow: "Baserunning watch",
    title: (ctx, abbrev) => `${abbrev} baserunning blunders`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "games-between-steals",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.onFirst,
    eyebrow: "Steal watch",
    title: () => "Swipe incoming?",
    message: defaultMessage,
  }),
  inningChange({
    statId: "games-between-home-runs",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.isLateInning,
    eyebrow: "Power drought",
    title: () => "Homer watch",
    message: defaultMessage,
  }),
  inningChange({
    statId: "back-to-back-hr-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) >= 6,
    eyebrow: "Power surge",
    title: () => "Back-to-back weather",
    message: defaultMessage,
  }),
  inningChange({
    statId: "back-to-back-hr-sequences",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) >= 6,
    eyebrow: "Power surge",
    title: () => "Back-to-back merchants",
    message: defaultMessage,
  }),
  inningChange({
    statId: "back-to-back-to-back-hr-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) >= 8,
    eyebrow: "Power surge",
    title: () => "Three in a row weather",
    message: defaultMessage,
  }),
  inningChange({
    statId: "cycle-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) >= 5,
    eyebrow: "Cycle watch",
    title: () => "Cycle weather",
    message: defaultMessage,
  }),
  inningChange({
    statId: "player-cycle-games",
    team: "offense",
    polarity: "either",
    match: (ctx) => totalRuns(ctx) >= 5,
    eyebrow: "Cycle watch",
    title: () => "Player cycle watch",
    message: defaultMessage,
  }),
  inningChange({
    statId: "max-hbp-in-game",
    team: "offense",
    polarity: "either",
    match: (ctx) => ctx.inning >= 5,
    eyebrow: "HBP watch",
    title: () => "Hit-by-pitch merchants",
    message: defaultMessage,
  }),
  inningChange({
    statId: "triple-plays-hit-into",
    team: "offense",
    polarity: "cursed",
    match: (ctx) => ctx.basesLoaded,
    eyebrow: "Triple play watch",
    title: () => "Triple play danger",
    message: defaultMessage,
  }),
  inningChange({
    statId: "triple-plays-turned",
    team: "defense",
    polarity: "elite",
    match: (ctx) => ctx.basesLoaded,
    eyebrow: "Triple play watch",
    title: (ctx, abbrev) => `${abbrev} triple-play artists`,
    message: defaultMessage,
  }),
  inningChange({
    statId: "triple-play-rate",
    team: "defense",
    polarity: "elite",
    match: (ctx) => ctx.basesLoaded && ctx.outs === 0,
    eyebrow: "Triple play watch",
    title: (ctx, abbrev) => `${abbrev} rare feat hunters`,
    message: defaultMessage,
  }),
];
