/* Generated by scripts/generate-wtbb-logo.mjs — do not hand-edit */
import { cn } from "@/lib/utils";

type WtbbMarkProps = {
  className?: string;
  withPlate?: boolean;
  title?: string;
};

/** Baseball + three spray arrows (0°, 22.5°, 45°) from center. */
export function WtbbMark({
  className,
  withPlate = false,
  title = "Where's That BB",
}: WtbbMarkProps) {
  return (
    <svg
      viewBox="0 0 128 128"
      className={cn("block shrink-0", className)}
      role="img"
      aria-label={title}
    >
      <title>{title}</title>
      {withPlate ? <rect width="128" height="128" rx="28" fill="#ede6d6" /> : null}
      <circle cx="36" cy="64" r="28" fill="#f4f1ea" stroke="currentColor" strokeWidth="2.8"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.2" strokeLinecap="round" opacity="0.45" d="M11.4 56.2C28.2 42.2, 43.8 42.2, 60.6 56.2"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M14.0 50.6L16.4 52.4L17.1 55.2"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M19.2 47.4L21.3 49.4L21.7 52.4"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M24.4 45.0L26.2 47.3L26.2 50.3"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M29.7 43.5L31.1 46.1L30.6 49.0"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M35.0 42.9L36.0 45.7L35.0 48.5"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M40.4 43.2L40.9 46.1L39.4 48.7"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M45.7 44.4L45.8 47.3L43.9 49.7"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M51.1 46.5L50.7 49.4L48.5 51.5"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M56.4 49.5L55.6 52.4L53.3 54.2"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.2" strokeLinecap="round" opacity="0.45" d="M11.4 71.8C28.2 85.8, 43.8 85.8, 60.6 71.8"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M17.1 72.8L16.4 75.6L14.0 77.4"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M21.7 75.6L21.3 78.6L19.2 80.6"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M26.2 77.7L26.2 80.7L24.4 83.0"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M30.6 79.0L31.1 81.9L29.7 84.5"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M35.0 79.5L36.0 82.3L35.0 85.1"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M39.4 79.3L40.9 81.9L40.4 84.8"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M43.9 78.3L45.8 80.7L45.7 83.6"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M48.5 76.5L50.7 78.6L51.1 81.5"/>
  <path fill="none" stroke="#c41e3a" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" d="M53.3 73.8L55.6 75.6L56.4 78.5"/>
  <g>
    <path fill="none" stroke="#1b4332" strokeWidth="3" strokeLinecap="round" d="M40.0 64.0L111.5 64.0"/>
    <path fill="#1b4332" d="M111.0 70.0L122.0 64.0L111.0 58.0Z"/>
    <path fill="none" stroke="#1b4332" strokeWidth="3" strokeLinecap="round" d="M39.7 62.5L105.8 35.1"/>
    <path fill="#1b4332" d="M107.6 40.8L115.5 31.1L103.0 29.8Z"/>
    <path fill="none" stroke="#1b4332" strokeWidth="3" strokeLinecap="round" d="M38.8 61.2L89.4 10.6"/>
    <path fill="#1b4332" d="M93.3 15.2L96.8 3.2L84.8 6.7Z"/>
  </g>
  <circle cx="36" cy="64" r="4.2" fill="#1b4332"/>
    </svg>
  );
}

/** @deprecated Use WtbbMark */
export const WtbbMonogram = WtbbMark;
