import { describe, expect, it } from "vitest";

import { rankPlayerOnTeam } from "@/lib/mlb/nerdStats/playerNerdBuild";
import type { NerdStatDefinition } from "@/lib/mlb/nerdStats/statDefinitions";
import type { PlayerNerdCounters } from "@/lib/mlb/nerdStats/types";

function makePlayer(
  overrides: Partial<PlayerNerdCounters> & Pick<PlayerNerdCounters, "playerId" | "name">,
): PlayerNerdCounters {
  return {
    teamId: 136,
    teamAbbrev: "SEA",
    gamesPlayed: 0,
    finalGamesWithFeed: 0,
    wins: 0,
    losses: 0,
    oneRunGames: 0,
    oneRunWins: 0,
    oneRunLosses: 0,
    extraInningGames: 0,
    extraInningWins: 0,
    extraInningLosses: 0,
    blowoutLosses: 0,
    blowoutWins: 0,
    shutoutGames: 0,
    tenPlusRunGames: 0,
    twoOrFewerRunGames: 0,
    comebackWins: 0,
    runsScored: 0,
    runsWithTwoOuts: 0,
    firstInningRuns: 0,
    lateInningRuns: 0,
    runsAllowed: 0,
    firstInningRunsAllowed: 0,
    lateInningRunsAllowed: 0,
    leadTakeNextInningRunsAllowed: 0,
    leadTakeNextInningOpportunities: 0,
    plateAppearances: 10,
    strikeouts: 0,
    walks: 0,
    intentWalks: 0,
    hbp: 0,
    sacFlies: 0,
    sacBunts: 0,
    gidp: 0,
    rallyKillerGidp: 0,
    gidpInduced: 0,
    triplePlays: 0,
    triplePlaysTurned: 0,
    triplePlayOpportunities: 0,
    walkoffBloopSingles: 0,
    walkoffWins: 0,
    walkoffLosses: 0,
    bloopSingles: 0,
    infieldSingles: 0,
    homeRuns: 0,
    softestHomeRunMph: null,
    shortestHomeRunFt: null,
    flarestHomeRunLa: null,
    hardestHitMph: null,
    moonshotHomeRuns: 0,
    noDoubterHomeRuns: 0,
    battedBallEvents: 0,
    barrelBalls: 0,
    chopBalls: 0,
    popupBalls: 0,
    hardHitBalls: 0,
    sweetSpotBalls: 0,
    weakContactBalls: 0,
    toppedContactBalls: 0,
    underContactBalls: 0,
    flareContactBalls: 0,
    solidContactBalls: 0,
    launchSpeedAngleSum: 0,
    launchSpeedAngleCount: 0,
    meatballsThrown: 0,
    meatballsSeen: 0,
    meatballsInPlay: 0,
    meatballsInPlayAllowed: 0,
    meatballsPunished: 0,
    meatballsPunishedAllowed: 0,
    meatballBarrels: 0,
    meatballBarrelsAllowed: 0,
    meatballWhiffs: 0,
    meatballWhiffsInduced: 0,
    exitVeloSum: 0,
    exitVeloCount: 0,
    launchAngleSum: 0,
    launchAngleCount: 0,
    batSpeedSum: 0,
    batSpeedCount: 0,
    pitchTypesThrown: {},
    stolenBases: 0,
    caughtStealing: 0,
    pickoffs: 0,
    balkBenefits: 0,
    wildPitchBenefits: 0,
    passedBallBenefits: 0,
    errorRunBenefits: 0,
    errorsCommitted: 0,
    fieldingErrors: 0,
    throwingErrors: 0,
    reachedOnError: 0,
    errorRunsAllowed: 0,
    errorGames: 0,
    multiErrorGames: 0,
    errorFreeGames: 0,
    basesLoadedNoRuns: 0,
    nobletigers: 0,
    nobletigersInduced: 0,
    cycleGames: 0,
    backToBackHrGames: 0,
    backToBackToBackHrGames: 0,
    goldenSombreros: 0,
    multiHrGamesAllowed: 0,
    immaculateInningVictims: 0,
    zeroWalkGames: 0,
    wallScraperHomeRuns: 0,
    leftOnBase: 0,
    lobNightmareGames: 0,
    pinchHitAttempts: 0,
    pinchHitHits: 0,
    pinchHitHomeRuns: 0,
    pinchHitChaos: 0,
    hardestHitAllowedMph: null,
    playerCycleGames: 0,
    maxHbpInGame: 0,
    noHitterBidRuined: 0,
    grandSlams: 0,
    insideTheParkHomeRuns: 0,
    eightPlusRunGames: 0,
    whiffFestGames: 0,
    leadoffHomeRuns: 0,
    doubles: 0,
    triples: 0,
    rispHits: 0,
    rispAtBats: 0,
    rispPlateAppearances: 0,
    fullCountHits: 0,
    fullCountAtBats: 0,
    fullCountWalks: 0,
    fullCountHbp: 0,
    fullCountSacFlies: 0,
    fullCountTotalBases: 0,
    firstPitchesSeen: 0,
    firstPitchesThrown: 0,
    firstPitchStrikes: 0,
    firstPitchStrikesThrown: 0,
    firstPitchBalls: 0,
    firstPitchBallsThrown: 0,
    firstPitchCalledStrikes: 0,
    firstPitchCalledStrikesInduced: 0,
    firstPitchSwingingStrikes: 0,
    firstPitchSwingingStrikesInduced: 0,
    ...overrides,
  } as PlayerNerdCounters;
}

const hrDef: NerdStatDefinition = {
  id: "home-runs",
  title: "Home Runs",
  subtitle: "test",
  category: "traditional",
  unit: "count",
  sort: "desc",
  compute: (c) => c.homeRuns,
  formatValue: (v) => String(v),
};

describe("rankPlayerOnTeam", () => {
  it("ranks higher values first for desc stats and ties share rank", () => {
    const teammates = [
      makePlayer({ playerId: 1, name: "A", homeRuns: 10 }),
      makePlayer({ playerId: 2, name: "B", homeRuns: 8 }),
      makePlayer({ playerId: 3, name: "C", homeRuns: 8 }),
      makePlayer({ playerId: 4, name: "D", homeRuns: 3 }),
    ];

    expect(rankPlayerOnTeam(1, teammates, hrDef)).toEqual({
      teamRank: 1,
      teamRankedCount: 4,
    });
    expect(rankPlayerOnTeam(2, teammates, hrDef)).toEqual({
      teamRank: 2,
      teamRankedCount: 4,
    });
    expect(rankPlayerOnTeam(3, teammates, hrDef)).toEqual({
      teamRank: 2,
      teamRankedCount: 4,
    });
    expect(rankPlayerOnTeam(4, teammates, hrDef)).toEqual({
      teamRank: 4,
      teamRankedCount: 4,
    });
  });
});
