import {
  formatCount,
  formatDegrees,
  formatFeet,
  formatGamesBetween,
  formatMph,
  formatPercent,
  formatRatePer1000,
  pct,
  ratePer1000,
} from "@/lib/mlb/nerdStats/format";
import type { NerdStatCategory, TeamNerdCounters } from "@/lib/mlb/nerdStats/types";

export interface NerdStatDefinition {
  id: string;
  title: string;
  subtitle: string;
  category: NerdStatCategory;
  sort: "asc" | "desc";
  unit: string;
  minGames?: number;
  compute: (counters: TeamNerdCounters) => number | null;
  formatValue: (value: number) => string;
}

export const NERD_STAT_DEFINITIONS: NerdStatDefinition[] = [
  // —— Drama ——
  {
    id: "walkoff-bloop-singles",
    title: "Walk-off Bloop Factory",
    subtitle: "Game-ending bloop singles. Higher = more chaos.",
    category: "drama",
    sort: "desc",
    unit: "walk-offs",
    compute: (c) => c.walkoffBloopSingles,
    formatValue: formatCount,
  },
  {
    id: "walk-off-wins",
    title: "Walk-off Winners",
    subtitle: "Games won on a walk-off play.",
    category: "drama",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.walkoffWins,
    formatValue: formatCount,
  },
  {
    id: "walk-off-losses",
    title: "Walk-off Wound Collectors",
    subtitle: "Games lost on an opponent walk-off.",
    category: "drama",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.walkoffLosses,
    formatValue: formatCount,
  },
  {
    id: "runs-with-two-outs-pct",
    title: "Two-Out Run Merchants",
    subtitle: "Share of runs scored with two outs.",
    category: "drama",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.runsWithTwoOuts, c.runsScored),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "one-run-games",
    title: "One-Run Nailbiters",
    subtitle: "Games decided by a single run.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.oneRunGames,
    formatValue: formatCount,
  },
  {
    id: "one-run-win-pct",
    title: "One-Run Clutch Factor",
    subtitle: "Win rate in one-run games.",
    category: "drama",
    sort: "desc",
    unit: "%",
    minGames: 5,
    compute: (c) => pct(c.oneRunWins, c.oneRunGames),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "extra-inning-games",
    title: "Bonus Baseball Enjoyers",
    subtitle: "Games that went to extras.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.extraInningGames,
    formatValue: formatCount,
  },
  {
    id: "extra-inning-win-pct",
    title: "Free Baseball Specialists",
    subtitle: "Win rate in extra-inning games.",
    category: "drama",
    sort: "desc",
    unit: "%",
    minGames: 3,
    compute: (c) => pct(c.extraInningWins, c.extraInningGames),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "comeback-wins",
    title: "Comeback Kids",
    subtitle: "Wins after trailing by 3+ runs at any point.",
    category: "drama",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.comebackWins,
    formatValue: formatCount,
  },
  {
    id: "pitcher-duel-games",
    title: "Pitcher Duel Participants",
    subtitle: "Games where the team scored 2 or fewer runs.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.twoOrFewerRunGames,
    formatValue: formatCount,
  },

  // —— Misfortune ——
  {
    id: "double-plays-hit-into",
    title: "GIDP Factory",
    subtitle: "Double plays hit into.",
    category: "misfortune",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.gidp,
    formatValue: formatCount,
  },
  {
    id: "rally-killer-gidp",
    title: "Rally Killers",
    subtitle: "GIDPs with a runner on second (or worse).",
    category: "misfortune",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.rallyKillerGidp,
    formatValue: formatCount,
  },
  {
    id: "triple-plays-hit-into",
    title: "Triple Play Magnet",
    subtitle: "Triple plays hit into.",
    category: "misfortune",
    sort: "desc",
    unit: "TP",
    compute: (c) => c.triplePlays,
    formatValue: formatCount,
  },
  {
    id: "triple-play-rate",
    title: "Triple Play Likelihood",
    subtitle: "Triple plays per 1,000 golden opportunities.",
    category: "misfortune",
    sort: "desc",
    unit: "per 1k",
    minGames: 20,
    compute: (c) => ratePer1000(c.triplePlays, c.triplePlayOpportunities),
    formatValue: (v) => formatRatePer1000(v),
  },
  {
    id: "hit-by-pitch",
    title: "Plunked Patrol",
    subtitle: "Hit-by-pitches absorbed.",
    category: "misfortune",
    sort: "desc",
    unit: "HBP",
    compute: (c) => c.hbp,
    formatValue: formatCount,
  },
  {
    id: "blowout-losses",
    title: "Blowout Loss Collector",
    subtitle: "Losses by five runs or more.",
    category: "misfortune",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.blowoutLosses,
    formatValue: formatCount,
  },
  {
    id: "shutout-victim",
    title: "Shutout Victims",
    subtitle: "Games where the team was held scoreless.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.shutoutGames,
    formatValue: formatCount,
  },
  {
    id: "golden-sombrero",
    title: "Golden Sombrero Society",
    subtitle: "Games with a batter striking out 4+ times.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.goldenSombreros,
    formatValue: formatCount,
  },
  {
    id: "multi-hr-games-allowed",
    title: "Long Ball Punching Bag",
    subtitle: "Games where opponents hit 3+ home runs.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.multiHrGamesAllowed,
    formatValue: formatCount,
  },
  {
    id: "immaculate-inning-victim",
    title: "Immaculate Inning Victims",
    subtitle: "Half-innings where all three outs were strikeouts.",
    category: "misfortune",
    sort: "desc",
    unit: "innings",
    compute: (c) => c.immaculateInningVictims,
    formatValue: formatCount,
  },

  // —— Baserunning ——
  {
    id: "games-between-steals",
    title: "Steal Drought",
    subtitle: "Average games between successful steals.",
    category: "baserunning",
    sort: "desc",
    unit: "games",
    minGames: 20,
    compute: (c) => (c.stolenBases > 0 ? c.finalGamesWithFeed / c.stolenBases : null),
    formatValue: formatGamesBetween,
  },
  {
    id: "steal-success-rate",
    title: "Swipe Success Rate",
    subtitle: "Stolen bases per steal attempt.",
    category: "baserunning",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.stolenBases, c.stolenBases + c.caughtStealing),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "steal-attempt-rate",
    title: "Green Light Fanatics",
    subtitle: "Steal attempts per game.",
    category: "baserunning",
    sort: "desc",
    unit: "per game",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0
        ? (c.stolenBases + c.caughtStealing) / c.finalGamesWithFeed
        : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "pickoffs-suffered",
    title: "Pickoff Punching Bag",
    subtitle: "Runners picked off.",
    category: "baserunning",
    sort: "desc",
    unit: "pickoffs",
    compute: (c) => c.pickoffs,
    formatValue: formatCount,
  },
  {
    id: "caught-stealing",
    title: "Caught Stealing Club",
    subtitle: "Runners thrown out stealing.",
    category: "baserunning",
    sort: "desc",
    unit: "CS",
    compute: (c) => c.caughtStealing,
    formatValue: formatCount,
  },
  {
    id: "baserunning-blunders",
    title: "TOOTBLAN Territory",
    subtitle: "Caught stealing plus pickoffs.",
    category: "baserunning",
    sort: "desc",
    unit: "outs",
    compute: (c) => c.caughtStealing + c.pickoffs,
    formatValue: formatCount,
  },

  // —— Contact ——
  {
    id: "softest-home-run",
    title: "Softest Dinger",
    subtitle: "Lowest exit velocity on a home run.",
    category: "contact",
    sort: "asc",
    unit: "mph",
    compute: (c) => c.softestHomeRunMph,
    formatValue: formatMph,
  },
  {
    id: "shortest-home-run",
    title: "Shortest Homer",
    subtitle: "Shortest measured home run distance.",
    category: "contact",
    sort: "asc",
    unit: "ft",
    compute: (c) => c.shortestHomeRunFt,
    formatValue: formatFeet,
  },
  {
    id: "flarest-home-run",
    title: "Flarest Dinger",
    subtitle: "Highest launch angle on a home run.",
    category: "contact",
    sort: "desc",
    unit: "°",
    compute: (c) => c.flarestHomeRunLa,
    formatValue: formatDegrees,
  },
  {
    id: "hardest-hit",
    title: "Hardest Hit",
    subtitle: "Highest exit velocity on any batted ball.",
    category: "contact",
    sort: "desc",
    unit: "mph",
    compute: (c) => c.hardestHitMph,
    formatValue: formatMph,
  },
  {
    id: "moonshot-hrs",
    title: "Moonshot Society",
    subtitle: "Home runs with launch angle above 45°.",
    category: "contact",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.moonshotHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "wall-scraper-hrs",
    title: "Wall Scrapers",
    subtitle: "Home runs under 340 feet.",
    category: "contact",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.wallScraperHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "no-doubter-hr-rate",
    title: "No-Doubter Rate",
    subtitle: "Share of homers that were absolute tanks.",
    category: "contact",
    sort: "desc",
    unit: "%",
    minGames: 10,
    compute: (c) => pct(c.noDoubterHomeRuns, c.homeRuns),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "barrel-rate",
    title: "Barrel Bureau",
    subtitle: "Barrels per batted-ball event.",
    category: "contact",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.barrelBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "chop-rate",
    title: "Chop Shop",
    subtitle: "Grounders under 5° launch angle.",
    category: "contact",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.chopBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "popup-rate",
    title: "Pop-up Factory",
    subtitle: "Fly balls over 50° launch angle.",
    category: "contact",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.popupBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "bloop-singles",
    title: "Bloop Single Artists",
    subtitle: "Flares, bloops, and cheapies that fell.",
    category: "contact",
    sort: "desc",
    unit: "bloops",
    compute: (c) => c.bloopSingles,
    formatValue: formatCount,
  },
  {
    id: "infield-singles",
    title: "Infield Chaos",
    subtitle: "Leg hits, choppers, and seeing-eye grounders.",
    category: "contact",
    sort: "desc",
    unit: "hits",
    compute: (c) => c.infieldSingles,
    formatValue: formatCount,
  },
  {
    id: "pitcher-hits",
    title: "Pitcher Hit Parade",
    subtitle: "Hits by pitchers (yes, really).",
    category: "contact",
    sort: "desc",
    unit: "hits",
    compute: (c) => c.pitcherHits,
    formatValue: formatCount,
  },
  {
    id: "games-between-home-runs",
    title: "Homer Drought",
    subtitle: "Average games between team home runs.",
    category: "contact",
    sort: "desc",
    unit: "games",
    minGames: 20,
    compute: (c) => (c.homeRuns > 0 ? c.finalGamesWithFeed / c.homeRuns : null),
    formatValue: formatGamesBetween,
  },

  // —— Defense ——
  {
    id: "gidp-induced",
    title: "GIDP Inducers",
    subtitle: "Double plays turned on opposing batters.",
    category: "defense",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.gidpInduced,
    formatValue: formatCount,
  },
  {
    id: "triple-plays-turned",
    title: "Triple Play Turners",
    subtitle: "Triple plays turned on defense.",
    category: "defense",
    sort: "desc",
    unit: "TP",
    compute: (c) => c.triplePlaysTurned,
    formatValue: formatCount,
  },

  // —— Chaos ——
  {
    id: "late-inning-runs",
    title: "Late-Inning Panic",
    subtitle: "Runs scored from the 8th inning on.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.lateInningRuns,
    formatValue: formatCount,
  },
  {
    id: "first-inning-runs",
    title: "First-Inning Ambush",
    subtitle: "Runs scored in the opening frame.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.firstInningRuns,
    formatValue: formatCount,
  },
  {
    id: "strikeout-rate",
    title: "True Outcome Enjoyers",
    subtitle: "Strikeout rate on plate appearances.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.strikeouts, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "walk-rate",
    title: "Free Pass Fan Club",
    subtitle: "Walk rate on plate appearances.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.walks, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "intent-walk-rate",
    title: "Intentional Walk Dealers",
    subtitle: "Intent walks per plate appearance.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.intentWalks, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "sac-fly-rate",
    title: "Sac Fly Merchants",
    subtitle: "Sacrifice flies per plate appearance.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    minGames: 20,
    compute: (c) => pct(c.sacFlies, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "sac-bunt-society",
    title: "Sac Bunt Society",
    subtitle: "Small-ball sacrifice bunts.",
    category: "chaos",
    sort: "desc",
    unit: "sacs",
    compute: (c) => c.sacBunts,
    formatValue: formatCount,
  },
  {
    id: "blowout-wins",
    title: "Blowout Bullies",
    subtitle: "Wins by five runs or more.",
    category: "chaos",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.blowoutWins,
    formatValue: formatCount,
  },
  {
    id: "ten-run-outbursts",
    title: "Ten-Run Tantrums",
    subtitle: "Games with 10+ runs scored.",
    category: "chaos",
    sort: "desc",
    unit: "games",
    compute: (c) => c.tenPlusRunGames,
    formatValue: formatCount,
  },
  {
    id: "zero-walk-games",
    title: "Patience Is Overrated",
    subtitle: "Games without a single walk drawn.",
    category: "chaos",
    sort: "desc",
    unit: "games",
    compute: (c) => c.zeroWalkGames,
    formatValue: formatCount,
  },
  {
    id: "balk-beneficiaries",
    title: "Balk Lottery Winners",
    subtitle: "Runs scored on balks.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.balkBenefits,
    formatValue: formatCount,
  },
  {
    id: "wild-pitch-runs",
    title: "Wild Pitch Beneficiaries",
    subtitle: "Runs scored on wild pitches.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.wildPitchBenefits,
    formatValue: formatCount,
  },
  {
    id: "passed-ball-runs",
    title: "Passed Ball Pirates",
    subtitle: "Runs scored on passed balls.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.passedBallBenefits,
    formatValue: formatCount,
  },
  {
    id: "error-assisted-runs",
    title: "Error-Assisted Runs",
    subtitle: "Runs scored with an error in the play.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.errorRunBenefits,
    formatValue: formatCount,
  },

  // —— Vibes ——
  {
    id: "cycle-games",
    title: "Cycle Game Club",
    subtitle: "Games where the team hit for the cycle.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.cycleGames,
    formatValue: formatCount,
  },
  {
    id: "back-to-back-hr-games",
    title: "Back-to-Back Bombers",
    subtitle: "Games with consecutive home runs.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.backToBackHrGames,
    formatValue: formatCount,
  },
  {
    id: "back-to-back-to-back-hr-games",
    title: "Three Straight Dingers",
    subtitle: "Games with three consecutive home runs.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.backToBackToBackHrGames,
    formatValue: formatCount,
  },
  {
    id: "bases-loaded-no-runs",
    title: "Bases Loaded, No Runs",
    subtitle: "Half-innings: ducks on the pond, zero scored.",
    category: "vibes",
    sort: "desc",
    unit: "innings",
    compute: (c) => c.basesLoadedNoRuns,
    formatValue: formatCount,
  },
];

export function getNerdStatDefinition(statId: string): NerdStatDefinition | undefined {
  return NERD_STAT_DEFINITIONS.find((stat) => stat.id === statId);
}

export function pickStatOfTheDay(season: number, stats: { id: string }[]): string {
  if (stats.length === 0) return NERD_STAT_DEFINITIONS[0]!.id;
  const dayOfYear = Math.floor(
    (Date.now() - new Date(`${season}-03-01T12:00:00Z`).getTime()) / 86_400_000,
  );
  const index = Math.abs(dayOfYear) % stats.length;
  return stats[index]!.id;
}
