import {
  formatBattingAverage,
  formatCount,
  formatDegrees,
  formatFeet,
  formatGamesBetween,
  formatMph,
  formatPercent,
  formatRatePer1000,
  formatRunDifferential,
  formatSlashStat,
  pct,
  rate,
  ratePer1000,
} from "@/lib/mlb/nerdStats/format";
import {
  CONTACT_QUALITY_NERD_STAT_DEFINITIONS,
  PITCH_TYPE_NERD_STAT_DEFINITIONS,
} from "@/lib/mlb/nerdStats/pitchTypeStatDefinitions";
import type { NerdStatCategory, TeamNerdCounters } from "@/lib/mlb/nerdStats/types";

export interface NerdStatDefinition {
  id: string;
  title: string;
  subtitle: string;
  category: NerdStatCategory;
  sort: "asc" | "desc";
  unit: string;
  formula?: string;
  minGames?: number;
  compute: (counters: TeamNerdCounters) => number | null;
  formatValue: (value: number) => string;
}

function fullCountObpDenominator(counters: TeamNerdCounters): number {
  return (
    counters.fullCountAtBats +
    counters.fullCountWalks +
    counters.fullCountHbp +
    counters.fullCountSacFlies
  );
}

function fullCountObpNumerator(counters: TeamNerdCounters): number {
  return counters.fullCountHits + counters.fullCountWalks + counters.fullCountHbp;
}

function computeFullCountObp(counters: TeamNerdCounters): number | null {
  return rate(fullCountObpNumerator(counters), fullCountObpDenominator(counters));
}

function computeFullCountSlg(counters: TeamNerdCounters): number | null {
  return rate(counters.fullCountTotalBases, counters.fullCountAtBats);
}

function computeFullCountOps(counters: TeamNerdCounters): number | null {
  const obp = computeFullCountObp(counters);
  const slg = computeFullCountSlg(counters);
  if (obp == null || slg == null) return null;
  return obp + slg;
}

/** Approximate at-bats from plate appearances and non-AB outcomes. */
function computeAtBats(counters: TeamNerdCounters): number {
  return (
    counters.plateAppearances -
    counters.walks -
    counters.hbp -
    counters.sacFlies -
    counters.sacBunts
  );
}

/** Batting average on balls in play: (H − HR) ÷ (AB − K − HR + SF). */
function computeBabip(counters: TeamNerdCounters): number | null {
  const atBats = computeAtBats(counters);
  const denominator = atBats - counters.strikeouts - counters.homeRuns + counters.sacFlies;
  return rate(counters.hits - counters.homeRuns, denominator);
}

/**
 * FanGraphs-style left-on-base percentage:
 * (H + BB + HBP − R) ÷ (H + BB + HBP − 1.4×HR) × 100.
 * Higher = more baserunners stranded.
 */
function computeLobPct(counters: TeamNerdCounters): number | null {
  const baserunners = counters.hits + counters.walks + counters.hbp;
  const numerator = baserunners - counters.runsScored;
  const denominator = baserunners - 1.4 * counters.homeRuns;
  return pct(numerator, denominator);
}

/** League-ish baselines used only to scale BABIP/LOB into the misfortune index. */
const BABIP_BASELINE = 0.3;
const LOB_PCT_BASELINE = 72;

export const NERD_STAT_DEFINITIONS: NerdStatDefinition[] = [
  // —— Drama ——
  {
    id: "walkoff-bloop-singles",
    title: "Walk-off Bloop Factory",
    subtitle: "Game-ending bloop singles. Higher = more chaos.",
    category: "drama",
    sort: "desc",
    unit: "walk-offs",
    compute: (c) => c.walkoffBloopSingles,
    formatValue: formatCount,
  },
  {
    id: "walk-off-wins",
    title: "Walk-off Winners",
    subtitle: "Games won on a walk-off play.",
    category: "drama",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.walkoffWins,
    formatValue: formatCount,
  },
  {
    id: "walk-off-losses",
    title: "Walk-off Wound Collectors",
    subtitle: "Games lost on an opponent walk-off.",
    category: "drama",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.walkoffLosses,
    formatValue: formatCount,
  },
  {
    id: "runs-with-two-outs-pct",
    title: "Two-Out Run Merchants",
    subtitle: "Share of runs scored with two outs.",
    category: "drama",
    sort: "desc",
    unit: "%",
    formula: "runs with 2 outs ÷ total runs scored × 100",
    minGames: 20,
    compute: (c) => pct(c.runsWithTwoOuts, c.runsScored),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "one-run-games",
    title: "One-Run Nailbiters",
    subtitle: "Games decided by a single run.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.oneRunGames,
    formatValue: formatCount,
  },
  {
    id: "one-run-win-pct",
    title: "One-Run Clutch Factor",
    subtitle: "Win rate in one-run games.",
    category: "drama",
    sort: "desc",
    unit: "%",
    formula: "one-run wins ÷ one-run games × 100",
    minGames: 5,
    compute: (c) => pct(c.oneRunWins, c.oneRunGames),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "extra-inning-games",
    title: "Bonus Baseball Enjoyers",
    subtitle: "Games that went to extras.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.extraInningGames,
    formatValue: formatCount,
  },
  {
    id: "extra-inning-win-pct",
    title: "Free Baseball Specialists",
    subtitle: "Win rate in extra-inning games.",
    category: "drama",
    sort: "desc",
    unit: "%",
    formula: "extra-inning wins ÷ extra-inning games × 100",
    minGames: 3,
    compute: (c) => pct(c.extraInningWins, c.extraInningGames),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "comeback-wins",
    title: "Comeback Kids",
    subtitle: "Wins after trailing by 3+ runs at any point.",
    category: "drama",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.comebackWins,
    formatValue: formatCount,
  },
  {
    id: "pitcher-duel-games",
    title: "Pitcher Duel Participants",
    subtitle: "Games where the team scored 2 or fewer runs.",
    category: "drama",
    sort: "desc",
    unit: "games",
    compute: (c) => c.twoOrFewerRunGames,
    formatValue: formatCount,
  },
  {
    id: "one-run-losses",
    title: "One-Run Heartbreakers",
    subtitle: "Losses by a single run.",
    category: "drama",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.oneRunLosses,
    formatValue: formatCount,
  },
  {
    id: "extra-inning-losses",
    title: "Extra-Inning Heartbreak",
    subtitle: "Losses in bonus baseball.",
    category: "drama",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.extraInningLosses,
    formatValue: formatCount,
  },

  // —— Misfortune ——
  {
    id: "double-plays-hit-into",
    title: "GIDP Factory",
    subtitle: "Double plays hit into.",
    category: "misfortune",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.gidp,
    formatValue: formatCount,
  },
  {
    id: "rally-killer-gidp",
    title: "Rally Killers",
    subtitle: "GIDPs with a runner on second (or worse).",
    category: "misfortune",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.rallyKillerGidp,
    formatValue: formatCount,
  },
  {
    id: "triple-plays-hit-into",
    title: "Triple Play Magnet",
    subtitle: "Triple plays hit into.",
    category: "misfortune",
    sort: "desc",
    unit: "TP",
    compute: (c) => c.triplePlays,
    formatValue: formatCount,
  },
  {
    id: "triple-play-rate",
    title: "Triple Play Likelihood",
    subtitle: "Triple plays per 1,000 golden opportunities.",
    category: "misfortune",
    sort: "desc",
    unit: "per 1k",
    formula: "triple plays hit into ÷ triple-play opportunities × 1,000",
    minGames: 20,
    compute: (c) => ratePer1000(c.triplePlays, c.triplePlayOpportunities),
    formatValue: (v) => formatRatePer1000(v),
  },
  {
    id: "hit-by-pitch",
    title: "Plunked Patrol",
    subtitle: "Hit-by-pitches absorbed.",
    category: "misfortune",
    sort: "desc",
    unit: "HBP",
    compute: (c) => c.hbp,
    formatValue: formatCount,
  },
  {
    id: "blowout-losses",
    title: "Blowout Loss Collector",
    subtitle: "Losses by five runs or more.",
    category: "misfortune",
    sort: "desc",
    unit: "losses",
    compute: (c) => c.blowoutLosses,
    formatValue: formatCount,
  },
  {
    id: "shutout-victim",
    title: "Shutout Victims",
    subtitle: "Games where the team was held scoreless.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.shutoutGames,
    formatValue: formatCount,
  },
  {
    id: "golden-sombrero",
    title: "Golden Sombrero Society",
    subtitle: "Games with a batter striking out 4+ times.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.goldenSombreros,
    formatValue: formatCount,
  },
  {
    id: "multi-hr-games-allowed",
    title: "Long Ball Punching Bag",
    subtitle: "Games where opponents hit 3+ home runs.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.multiHrGamesAllowed,
    formatValue: formatCount,
  },
  {
    id: "immaculate-inning-victim",
    title: "Immaculate Inning Victims",
    subtitle: "Half-innings where all three outs were strikeouts.",
    category: "misfortune",
    sort: "desc",
    unit: "innings",
    compute: (c) => c.immaculateInningVictims,
    formatValue: formatCount,
  },
  {
    id: "post-lead-runs-allowed",
    title: "Lead Hangover",
    subtitle: "Runs allowed in the half-inning right after taking a lead.",
    category: "misfortune",
    sort: "desc",
    unit: "runs",
    formula: "runs allowed in the next defensive half after taking a lead",
    compute: (c) => c.leadTakeNextInningRunsAllowed,
    formatValue: formatCount,
  },
  {
    id: "post-lead-runs-per-chance",
    title: "Lead Hangover Rate",
    subtitle: "Average runs allowed in the half after taking a lead.",
    category: "misfortune",
    sort: "desc",
    unit: "runs/half",
    formula: "post-lead runs allowed ÷ post-lead defensive halves",
    minGames: 20,
    compute: (c) =>
      rate(c.leadTakeNextInningRunsAllowed, c.leadTakeNextInningOpportunities),
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "babip",
    title: "BABIP",
    subtitle: "Batting average on balls in play. Lower = fewer hits finding grass.",
    category: "misfortune",
    sort: "asc",
    unit: "AVG",
    formula: "(H − HR) ÷ (AB − K − HR + SF)",
    minGames: 20,
    compute: computeBabip,
    formatValue: formatBattingAverage,
  },
  {
    id: "lob-pct",
    title: "LOB%",
    subtitle: "Share of baserunners left on base. Higher = more stranded traffic.",
    category: "misfortune",
    sort: "desc",
    unit: "%",
    formula: "(H + BB + HBP − R) ÷ (H + BB + HBP − 1.4×HR) × 100",
    minGames: 20,
    compute: computeLobPct,
    formatValue: (v) => formatPercent(v),
  },

  // —— Baserunning ——
  {
    id: "games-between-steals",
    title: "Steal Drought",
    subtitle: "Average games between successful steals.",
    category: "baserunning",
    sort: "desc",
    unit: "games",
    formula: "games with play-by-play feed ÷ stolen bases",
    minGames: 20,
    compute: (c) => (c.stolenBases > 0 ? c.finalGamesWithFeed / c.stolenBases : null),
    formatValue: formatGamesBetween,
  },
  {
    id: "steal-success-rate",
    title: "Swipe Success Rate",
    subtitle: "Stolen bases per steal attempt.",
    category: "baserunning",
    sort: "desc",
    unit: "%",
    formula: "stolen bases ÷ (stolen bases + caught stealing) × 100",
    minGames: 20,
    compute: (c) => pct(c.stolenBases, c.stolenBases + c.caughtStealing),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "steal-attempt-rate",
    title: "Green Light Fanatics",
    subtitle: "Steal attempts per game.",
    category: "baserunning",
    sort: "desc",
    unit: "per game",
    formula: "(stolen bases + caught stealing) ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0
        ? (c.stolenBases + c.caughtStealing) / c.finalGamesWithFeed
        : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "pickoffs-suffered",
    title: "Pickoff Punching Bag",
    subtitle: "Runners picked off.",
    category: "baserunning",
    sort: "desc",
    unit: "pickoffs",
    compute: (c) => c.pickoffs,
    formatValue: formatCount,
  },
  {
    id: "caught-stealing",
    title: "Caught Stealing Club",
    subtitle: "Runners thrown out stealing.",
    category: "baserunning",
    sort: "desc",
    unit: "CS",
    compute: (c) => c.caughtStealing,
    formatValue: formatCount,
  },
  {
    id: "baserunning-blunders",
    title: "TOOTBLAN Territory",
    subtitle: "Caught stealing plus pickoffs.",
    category: "baserunning",
    sort: "desc",
    unit: "outs",
    compute: (c) => c.caughtStealing + c.pickoffs,
    formatValue: formatCount,
  },

  // —— Contact ——
  {
    id: "softest-home-run",
    title: "Softest Dinger",
    subtitle: "Lowest exit velocity on a home run.",
    category: "contact",
    sort: "asc",
    unit: "mph",
    formula: "Minimum exit velocity on any home run",
    compute: (c) => c.softestHomeRunMph,
    formatValue: formatMph,
  },
  {
    id: "shortest-home-run",
    title: "Shortest Homer",
    subtitle: "Shortest measured home run distance.",
    category: "contact",
    sort: "asc",
    unit: "ft",
    formula: "Shortest Statcast distance on any home run",
    compute: (c) => c.shortestHomeRunFt,
    formatValue: formatFeet,
  },
  {
    id: "flarest-home-run",
    title: "Flarest Dinger",
    subtitle: "Highest launch angle on a home run.",
    category: "contact",
    sort: "desc",
    unit: "°",
    formula: "Highest launch angle on any home run",
    compute: (c) => c.flarestHomeRunLa,
    formatValue: formatDegrees,
  },
  {
    id: "hardest-hit",
    title: "Hardest Hit",
    subtitle: "Highest exit velocity on any batted ball.",
    category: "contact",
    sort: "desc",
    unit: "mph",
    formula: "Maximum exit velocity on any batted ball",
    compute: (c) => c.hardestHitMph,
    formatValue: formatMph,
  },
  {
    id: "moonshot-hrs",
    title: "Moonshot Society",
    subtitle: "Home runs with launch angle above 45°.",
    category: "contact",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.moonshotHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "wall-scraper-hrs",
    title: "Wall Scrapers",
    subtitle: "Home runs under 340 feet.",
    category: "contact",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.wallScraperHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "no-doubter-hr-rate",
    title: "No-Doubter Rate",
    subtitle: "Share of homers that were absolute tanks.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "no-doubter homers (105+ mph, 20–35° LA) ÷ total homers × 100",
    minGames: 10,
    compute: (c) => pct(c.noDoubterHomeRuns, c.homeRuns),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "barrel-rate",
    title: "Barrel Bureau",
    subtitle: "Barrels per batted-ball event.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "barrels (98+ mph, 8–50° LA) ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.barrelBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "how-was-that-hit",
    title: "How Was That Hit?",
    subtitle: "Average Statcast contact grade (1 Weak → 6 Barrel).",
    category: "contact",
    sort: "desc",
    unit: "grade",
    formula: "average launch_speed_angle (1–6) on tracked batted balls",
    minGames: 20,
    compute: (c) =>
      c.launchSpeedAngleCount > 0
        ? c.launchSpeedAngleSum / c.launchSpeedAngleCount
        : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "solid-plus-rate",
    title: "Solid-Plus Contact",
    subtitle: "Share of batted balls that were solid contact or barrels.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "(solid contact + barrels) ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.solidContactBalls + c.barrelBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "weak-contact-rate",
    title: "Weak Contact Club",
    subtitle: "Share of batted balls graded Weak (launch_speed_angle 1).",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "weak contact ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.weakContactBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "hard-hit-rate",
    title: "Hard-Hit Merchants",
    subtitle: "Batted balls at 95+ mph exit velocity.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "hard-hit balls (EV ≥ 95) ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.hardHitBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "sweet-spot-rate",
    title: "Sweet Spot Society",
    subtitle: "Batted balls launched between 8° and 32°.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "sweet-spot balls (LA 8–32°) ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.sweetSpotBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "meatballs-punished",
    title: "Meatballs Punished",
    subtitle: "Hits on heart-of-zone pitches put in play.",
    category: "contact",
    sort: "desc",
    unit: "hits",
    formula: "hits on meatball pitches (middle ~2/3 plate, middle third of zone)",
    compute: (c) => c.meatballsPunished,
    formatValue: formatCount,
  },
  {
    id: "meatball-punish-rate",
    title: "Meatball Punishment Rate",
    subtitle: "Hit rate when a meatball is put in play.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "hits on meatballs in play ÷ meatballs in play × 100",
    minGames: 20,
    compute: (c) => pct(c.meatballsPunished, c.meatballsInPlay),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "meatball-barrel-rate",
    title: "Meatball Barrel Rate",
    subtitle: "Barrels per meatball put in play.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "barrels on meatballs ÷ meatballs in play × 100",
    minGames: 20,
    compute: (c) => pct(c.meatballBarrels, c.meatballsInPlay),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "meatballs-thrown",
    title: "Meatballs Thrown",
    subtitle: "Heart-of-zone pitches served up by the staff.",
    category: "defense",
    sort: "desc",
    unit: "pitches",
    formula: "pitches in the heart of the zone (middle ~2/3 plate, middle third of zone)",
    compute: (c) => c.meatballsThrown,
    formatValue: formatCount,
  },
  {
    id: "meatball-rate",
    title: "Meatball Rate",
    subtitle: "Share of pitches thrown that were meatballs.",
    category: "defense",
    sort: "desc",
    unit: "%",
    formula: "meatballs thrown ÷ pitches thrown × 100",
    minGames: 20,
    compute: (c) => pct(c.meatballsThrown, c.pitchesThrown),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "meatballs-punished-allowed",
    title: "Meatballs Served Hot",
    subtitle: "Hits allowed on meatball pitches put in play.",
    category: "defense",
    sort: "desc",
    unit: "hits",
    formula: "opponent hits on meatball pitches put in play",
    compute: (c) => c.meatballsPunishedAllowed,
    formatValue: formatCount,
  },
  {
    id: "meatball-whiff-rate",
    title: "Meatball Whiff Rate",
    subtitle: "Swinging-strike rate on meatballs seen.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "swinging strikes on meatballs ÷ meatballs seen × 100",
    minGames: 20,
    compute: (c) => pct(c.meatballWhiffs, c.meatballsSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "chop-rate",
    title: "Chop Shop",
    subtitle: "Grounders under 5° launch angle.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "grounders under 5° launch angle ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.chopBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "popup-rate",
    title: "Pop-up Factory",
    subtitle: "Fly balls over 50° launch angle.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "fly balls over 50° launch angle ÷ batted-ball events × 100",
    minGames: 20,
    compute: (c) => pct(c.popupBalls, c.battedBallEvents),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "bloop-singles",
    title: "Bloop Single Artists",
    subtitle: "Flares, bloops, and cheapies that fell.",
    category: "contact",
    sort: "desc",
    unit: "bloops",
    compute: (c) => c.bloopSingles,
    formatValue: formatCount,
  },
  {
    id: "infield-singles",
    title: "Infield Chaos",
    subtitle: "Leg hits, choppers, and seeing-eye grounders.",
    category: "contact",
    sort: "desc",
    unit: "hits",
    compute: (c) => c.infieldSingles,
    formatValue: formatCount,
  },
  {
    id: "games-between-home-runs",
    title: "Homer Drought",
    subtitle: "Average games between team home runs.",
    category: "contact",
    sort: "desc",
    unit: "games",
    formula: "games with play-by-play feed ÷ team home runs",
    minGames: 20,
    compute: (c) => (c.homeRuns > 0 ? c.finalGamesWithFeed / c.homeRuns : null),
    formatValue: formatGamesBetween,
  },

  // —— Defense ——
  {
    id: "gidp-induced",
    title: "GIDP Inducers",
    subtitle: "Double plays turned on opposing batters.",
    category: "defense",
    sort: "desc",
    unit: "GIDP",
    compute: (c) => c.gidpInduced,
    formatValue: formatCount,
  },
  {
    id: "triple-plays-turned",
    title: "Triple Play Turners",
    subtitle: "Triple plays turned on defense.",
    category: "defense",
    sort: "desc",
    unit: "TP",
    compute: (c) => c.triplePlaysTurned,
    formatValue: formatCount,
  },
  {
    id: "hardest-hit-allowed",
    title: "Hardest Hit Allowed",
    subtitle: "Highest exit velocity surrendered on contact.",
    category: "defense",
    sort: "desc",
    unit: "mph",
    formula: "Maximum exit velocity allowed on any batted ball",
    compute: (c) => c.hardestHitAllowedMph,
    formatValue: formatMph,
  },
  {
    id: "no-hitter-bid-ruined",
    title: "No-Hitter Bid Ruiners",
    subtitle: "Games where the first hit came after 6 hitless innings.",
    category: "defense",
    sort: "desc",
    unit: "games",
    compute: (c) => c.noHitterBidRuined,
    formatValue: formatCount,
  },
  {
    id: "errors-committed",
    title: "Error Factory",
    subtitle: "Total fielding and throwing errors committed.",
    category: "defense",
    sort: "desc",
    unit: "errors",
    compute: (c) => c.errorsCommitted,
    formatValue: formatCount,
  },
  {
    id: "errors-per-game",
    title: "Errors Per Game",
    subtitle: "Average errors committed per game.",
    category: "defense",
    sort: "desc",
    unit: "E/G",
    formula: "errors committed ÷ games with feed",
    minGames: 20,
    compute: (c) => (c.finalGamesWithFeed > 0 ? c.errorsCommitted / c.finalGamesWithFeed : null),
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "fielding-errors",
    title: "Butterfingers Club",
    subtitle: "Fielding errors charged on defense.",
    category: "defense",
    sort: "desc",
    unit: "errors",
    compute: (c) => c.fieldingErrors,
    formatValue: formatCount,
  },
  {
    id: "throwing-errors",
    title: "Launching Pad Arms",
    subtitle: "Throwing errors on defense.",
    category: "defense",
    sort: "desc",
    unit: "errors",
    compute: (c) => c.throwingErrors,
    formatValue: formatCount,
  },
  {
    id: "error-runs-allowed",
    title: "Error Run Donors",
    subtitle: "Runs allowed on plays with an error.",
    category: "defense",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.errorRunsAllowed,
    formatValue: formatCount,
  },
  {
    id: "error-games",
    title: "Sloppy Defense Days",
    subtitle: "Games with at least one error committed.",
    category: "defense",
    sort: "desc",
    unit: "games",
    compute: (c) => c.errorGames,
    formatValue: formatCount,
  },
  {
    id: "multi-error-games",
    title: "Multi-Error Meltdowns",
    subtitle: "Games with two or more errors committed.",
    category: "defense",
    sort: "desc",
    unit: "games",
    compute: (c) => c.multiErrorGames,
    formatValue: formatCount,
  },
  {
    id: "error-free-games",
    title: "Clean Glove Crew",
    subtitle: "Games played without committing an error.",
    category: "defense",
    sort: "desc",
    unit: "games",
    compute: (c) => c.errorFreeGames,
    formatValue: formatCount,
  },
  {
    id: "error-free-rate",
    title: "Error-Free Rate",
    subtitle: "Share of games without an error committed.",
    category: "defense",
    sort: "desc",
    unit: "%",
    formula: "error-free games ÷ games with feed × 100",
    minGames: 20,
    compute: (c) => pct(c.errorFreeGames, c.finalGamesWithFeed),
    formatValue: (v) => formatPercent(v),
  },

  // —— Chaos ——
  {
    id: "late-inning-runs",
    title: "Late-Inning Panic",
    subtitle: "Runs scored from the 8th inning on.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.lateInningRuns,
    formatValue: formatCount,
  },
  {
    id: "first-inning-runs",
    title: "First-Inning Ambush",
    subtitle: "Runs scored in the opening frame.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.firstInningRuns,
    formatValue: formatCount,
  },
  {
    id: "first-inning-runs-allowed",
    title: "First-Inning Leaks",
    subtitle: "Runs allowed in the opening frame.",
    category: "defense",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.firstInningRunsAllowed,
    formatValue: formatCount,
  },
  {
    id: "late-inning-runs-allowed",
    title: "Late-Inning Leaks",
    subtitle: "Runs allowed from the 8th inning on.",
    category: "defense",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.lateInningRunsAllowed,
    formatValue: formatCount,
  },
  {
    id: "strikeout-rate",
    title: "True Outcome Enjoyers",
    subtitle: "Strikeout rate on plate appearances.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "strikeouts ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.strikeouts, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "walk-rate",
    title: "Free Pass Fan Club",
    subtitle: "Walk rate on plate appearances.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "walks ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.walks, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "intent-walk-rate",
    title: "Intentional Walk Dealers",
    subtitle: "Intent walks per plate appearance.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "intent walks ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.intentWalks, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "sac-fly-rate",
    title: "Sac Fly Merchants",
    subtitle: "Sacrifice flies per plate appearance.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "sacrifice flies ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.sacFlies, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "sac-bunt-society",
    title: "Sac Bunt Society",
    subtitle: "Small-ball sacrifice bunts.",
    category: "chaos",
    sort: "desc",
    unit: "sacs",
    compute: (c) => c.sacBunts,
    formatValue: formatCount,
  },
  {
    id: "blowout-wins",
    title: "Blowout Bullies",
    subtitle: "Wins by five runs or more.",
    category: "chaos",
    sort: "desc",
    unit: "wins",
    compute: (c) => c.blowoutWins,
    formatValue: formatCount,
  },
  {
    id: "ten-run-outbursts",
    title: "Ten-Run Tantrums",
    subtitle: "Games with 10+ runs scored.",
    category: "chaos",
    sort: "desc",
    unit: "games",
    compute: (c) => c.tenPlusRunGames,
    formatValue: formatCount,
  },
  {
    id: "zero-walk-games",
    title: "Patience Is Overrated",
    subtitle: "Games without a single walk drawn.",
    category: "chaos",
    sort: "desc",
    unit: "games",
    compute: (c) => c.zeroWalkGames,
    formatValue: formatCount,
  },
  {
    id: "balk-beneficiaries",
    title: "Balk Lottery Winners",
    subtitle: "Runs scored on balks.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.balkBenefits,
    formatValue: formatCount,
  },
  {
    id: "wild-pitch-runs",
    title: "Wild Pitch Beneficiaries",
    subtitle: "Runs scored on wild pitches.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.wildPitchBenefits,
    formatValue: formatCount,
  },
  {
    id: "passed-ball-runs",
    title: "Passed Ball Pirates",
    subtitle: "Runs scored on passed balls.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.passedBallBenefits,
    formatValue: formatCount,
  },
  {
    id: "error-assisted-runs",
    title: "Error-Assisted Runs",
    subtitle: "Runs scored with an error in the play.",
    category: "chaos",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.errorRunBenefits,
    formatValue: formatCount,
  },
  {
    id: "reached-on-error",
    title: "Reached on Error Merchants",
    subtitle: "Plate appearances where the batter reached on a fielding error.",
    category: "chaos",
    sort: "desc",
    unit: "ROE",
    compute: (c) => c.reachedOnError,
    formatValue: formatCount,
  },

  // —— Vibes ——
  {
    id: "cycle-games",
    title: "Cycle Game Club",
    subtitle: "Games where the team hit for the cycle.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.cycleGames,
    formatValue: formatCount,
  },
  {
    id: "back-to-back-hr-games",
    title: "Back-to-Back Bombers",
    subtitle: "Games with consecutive home runs.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.backToBackHrGames,
    formatValue: formatCount,
  },
  {
    id: "back-to-back-to-back-hr-games",
    title: "Three Straight Dingers",
    subtitle: "Games with three consecutive home runs.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.backToBackToBackHrGames,
    formatValue: formatCount,
  },
  {
    id: "bases-loaded-no-runs",
    title: "Bases Loaded, No Runs",
    subtitle: "Half-innings: ducks on the pond, zero scored.",
    category: "vibes",
    sort: "desc",
    unit: "innings",
    compute: (c) => c.basesLoadedNoRuns,
    formatValue: formatCount,
  },
  {
    id: "left-on-base",
    title: "LOB Stranded",
    subtitle: "Total runners left on base.",
    category: "vibes",
    sort: "desc",
    unit: "LOB",
    compute: (c) => c.leftOnBase,
    formatValue: formatCount,
  },
  {
    id: "lob-nightmare-games",
    title: "LOB Nightmares",
    subtitle: "Games with 10+ runners left on base.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    compute: (c) => c.lobNightmareGames,
    formatValue: formatCount,
  },
  {
    id: "player-cycle-games",
    title: "Individual Cycle Club",
    subtitle: "Games where one batter hit for the cycle.",
    category: "vibes",
    sort: "desc",
    unit: "games",
    formula: "One batter records a single, double, triple, and home run in the same game",
    compute: (c) => c.playerCycleGames,
    formatValue: formatCount,
  },
  {
    id: "pinch-hit-chaos",
    title: "Pinch-Hit Chaos",
    subtitle: "Pinch appearances ending in hit, HBP, HR, or K.",
    category: "vibes",
    sort: "desc",
    unit: "events",
    compute: (c) => c.pinchHitChaos,
    formatValue: formatCount,
  },
  {
    id: "pinch-hit-hits",
    title: "Pinch-Hit Heroes",
    subtitle: "Hits by pinch hitters.",
    category: "vibes",
    sort: "desc",
    unit: "hits",
    compute: (c) => c.pinchHitHits,
    formatValue: formatCount,
  },
  {
    id: "max-hbp-in-game",
    title: "Plunked the Most (One Game)",
    subtitle: "Most hit-by-pitches absorbed in a single game.",
    category: "misfortune",
    sort: "desc",
    unit: "HBP",
    compute: (c) => c.maxHbpInGame,
    formatValue: formatCount,
  },
  {
    id: "chaos-luck-index",
    title: "Chaos Luck Index",
    subtitle: "Walk-offs, comeback wins, and gift runs minus misery per game.",
    category: "chaos",
    sort: "desc",
    unit: "index",
    formula:
      "(walk-off wins×3 + comeback wins×2 + error/balk/WP/PB runs − blowout losses − shutouts − golden sombreros) ÷ games with feed",
    minGames: 20,
    compute: (c) => {
      if (c.finalGamesWithFeed <= 0) return null;
      const luck =
        c.walkoffWins * 3 +
        c.comebackWins * 2 +
        c.errorRunBenefits +
        c.balkBenefits +
        c.wildPitchBenefits +
        c.passedBallBenefits;
      const misery = c.blowoutLosses + c.shutoutGames + c.goldenSombreros;
      return (luck - misery) / c.finalGamesWithFeed;
    },
    formatValue: (v) => v.toFixed(2),
  },

  // —— Derived rates & composite indices ——
  {
    id: "win-percentage",
    title: "Win Percentage",
    subtitle: "Plain old wins divided by games played.",
    category: "traditional",
    sort: "desc",
    unit: "%",
    formula: "wins ÷ games played × 100",
    minGames: 20,
    compute: (c) => pct(c.wins, c.gamesPlayed),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "runs-scored",
    title: "Runs Scored",
    subtitle: "Total runs plated — the RS column from the standings page.",
    category: "traditional",
    sort: "desc",
    unit: "runs",
    compute: (c) => c.runsScored,
    formatValue: formatCount,
  },
  {
    id: "runs-allowed",
    title: "Runs Allowed",
    subtitle: "Total runs surrendered — the RA column from the standings page.",
    category: "traditional",
    sort: "asc",
    unit: "runs",
    compute: (c) => c.runsAllowed,
    formatValue: formatCount,
  },
  {
    id: "run-differential",
    title: "Run Differential",
    subtitle: "Runs scored minus runs allowed — the +/- column.",
    category: "traditional",
    sort: "desc",
    unit: "runs",
    formula: "runs scored − runs allowed",
    compute: (c) => c.runsScored - c.runsAllowed,
    formatValue: formatRunDifferential,
  },
  {
    id: "runs-per-game",
    title: "Run Factory",
    subtitle: "Average runs scored per game with a full feed.",
    category: "traditional",
    sort: "desc",
    unit: "R/G",
    formula: "runs scored ÷ games with play-by-play feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.runsScored / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "runs-allowed-per-game",
    title: "Runs Allowed Per Game",
    subtitle: "Average runs surrendered per game with a full feed.",
    category: "traditional",
    sort: "asc",
    unit: "R/G",
    formula: "runs allowed ÷ games with play-by-play feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.runsAllowed / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "three-true-outcomes-rate",
    title: "Three True Outcomes Enjoyers",
    subtitle: "Strikeouts, walks, and homers per plate appearance.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "(strikeouts + walks + home runs) ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.strikeouts + c.walks + c.homeRuns, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "gidp-rate",
    title: "Double Play Rate",
    subtitle: "GIDPs per plate appearance.",
    category: "misfortune",
    sort: "desc",
    unit: "%",
    formula: "GIDP ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.gidp, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "hr-per-pa",
    title: "Homer Rate",
    subtitle: "Home runs per plate appearance.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "home runs ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.homeRuns, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "small-ball-score",
    title: "Small Ball Score",
    subtitle: "Sac bunts, sac flies, and stolen bases combined.",
    category: "baserunning",
    sort: "desc",
    unit: "plays",
    compute: (c) => c.sacBunts + c.sacFlies + c.stolenBases,
    formatValue: formatCount,
  },
  {
    id: "pinch-hit-success-rate",
    title: "Pinch-Hit Success",
    subtitle: "Pinch hits divided by pinch appearances.",
    category: "vibes",
    sort: "desc",
    unit: "%",
    formula: "pinch hits ÷ pinch attempts × 100",
    minGames: 10,
    compute: (c) => pct(c.pinchHitHits, c.pinchHitAttempts),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "first-inning-run-share",
    title: "First-Inning Ambush Rate",
    subtitle: "Share of runs scored in the opening frame.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "first-inning runs ÷ total runs scored × 100",
    minGames: 20,
    compute: (c) => pct(c.firstInningRuns, c.runsScored),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "late-inning-run-share",
    title: "Late-Inning Panic Rate",
    subtitle: "Share of runs scored from the 8th on.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "8th-inning+ runs ÷ total runs scored × 100",
    minGames: 20,
    compute: (c) => pct(c.lateInningRuns, c.runsScored),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "first-inning-runs-allowed-share",
    title: "First-Inning Leak Rate",
    subtitle: "Share of runs allowed in the opening frame.",
    category: "defense",
    sort: "desc",
    unit: "%",
    formula: "first-inning runs allowed ÷ total runs allowed × 100",
    minGames: 20,
    compute: (c) => pct(c.firstInningRunsAllowed, c.runsAllowed),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "late-inning-runs-allowed-share",
    title: "Late-Inning Leak Rate",
    subtitle: "Share of runs allowed from the 8th on.",
    category: "defense",
    sort: "desc",
    unit: "%",
    formula: "8th-inning+ runs allowed ÷ total runs allowed × 100",
    minGames: 20,
    compute: (c) => pct(c.lateInningRunsAllowed, c.runsAllowed),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "lob-per-game",
    title: "LOB Per Game",
    subtitle: "Runners left on base per game.",
    category: "vibes",
    sort: "desc",
    unit: "LOB/G",
    formula: "total LOB ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.leftOnBase / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "misfortune-index",
    title: "Misfortune Index",
    subtitle:
      "Close-loss heartbreak, shutouts, and bad BABIP/LOB% luck — not blowouts or garden-variety GIDPs.",
    category: "misfortune",
    sort: "desc",
    unit: "index",
    formula:
      "(3×one-run losses + 2×walk-off losses + extra-inning losses + shutouts + golden sombreros) ÷ games with feed + (0.300 − BABIP)×5 + (LOB% − 72)÷20",
    minGames: 20,
    compute: (c) => {
      if (c.finalGamesWithFeed <= 0) return null;
      const babip = computeBabip(c);
      const lobPct = computeLobPct(c);
      if (babip == null || lobPct == null) return null;
      const heartbreak =
        c.oneRunLosses * 3 +
        c.walkoffLosses * 2 +
        c.extraInningLosses +
        c.shutoutGames +
        c.goldenSombreros;
      const babipMisfortune = (BABIP_BASELINE - babip) * 5;
      const lobMisfortune = (lobPct - LOB_PCT_BASELINE) / 20;
      return heartbreak / c.finalGamesWithFeed + babipMisfortune + lobMisfortune;
    },
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "grand-slams",
    title: "Grand Slam Society",
    subtitle: "Bases-clearing bombs.",
    category: "vibes",
    sort: "desc",
    unit: "slams",
    compute: (c) => c.grandSlams,
    formatValue: formatCount,
  },
  {
    id: "inside-the-park-hrs",
    title: "Inside-the-Park Club",
    subtitle: "Homers where the batter actually had to run.",
    category: "vibes",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.insideTheParkHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "eight-plus-run-games",
    title: "Slugfest Specialists",
    subtitle: "Games with 8+ runs scored.",
    category: "chaos",
    sort: "desc",
    unit: "games",
    compute: (c) => c.eightPlusRunGames,
    formatValue: formatCount,
  },
  {
    id: "whiff-fest-games",
    title: "Whiff Fest Fridays",
    subtitle: "Games with 12+ team strikeouts.",
    category: "misfortune",
    sort: "desc",
    unit: "games",
    compute: (c) => c.whiffFestGames,
    formatValue: formatCount,
  },
  {
    id: "leadoff-homers",
    title: "Leadoff Launchers",
    subtitle: "Home runs leading off a half-inning.",
    category: "contact",
    sort: "desc",
    unit: "HR",
    compute: (c) => c.leadoffHomeRuns,
    formatValue: formatCount,
  },
  {
    id: "doubles-factory",
    title: "Doubles Factory",
    subtitle: "Two-baggers hit.",
    category: "contact",
    sort: "desc",
    unit: "2B",
    compute: (c) => c.doubles,
    formatValue: formatCount,
  },
  {
    id: "triples-helmet",
    title: "Triples Helmet Club",
    subtitle: "Three-baggers legged out.",
    category: "contact",
    sort: "desc",
    unit: "3B",
    compute: (c) => c.triples,
    formatValue: formatCount,
  },
  {
    id: "extra-base-rate",
    title: "Extra-Base Rate",
    subtitle: "Doubles, triples, and homers per plate appearance.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "(doubles + triples + home runs) ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.doubles + c.triples + c.homeRuns, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "risp-batting",
    title: "RISP Merchants",
    subtitle: "Batting average with runners in scoring position.",
    category: "drama",
    sort: "desc",
    unit: "AVG",
    formula: "hits with RISP ÷ at-bats with RISP",
    minGames: 20,
    compute: (c) => rate(c.rispHits, c.rispAtBats),
    formatValue: formatBattingAverage,
  },
  {
    id: "full-count-obp",
    title: "Full Count On-Base Artists",
    subtitle: "On-base percentage in plate appearances that reached 3-2.",
    category: "drama",
    sort: "desc",
    unit: "OBP",
    formula: "(H + BB + HBP) ÷ (AB + BB + HBP + SF)",
    minGames: 20,
    compute: computeFullCountObp,
    formatValue: formatSlashStat,
  },
  {
    id: "full-count-slg",
    title: "Full Count Slug Squad",
    subtitle: "Slugging percentage in plate appearances that reached 3-2.",
    category: "drama",
    sort: "desc",
    unit: "SLG",
    formula: "total bases ÷ at-bats",
    minGames: 20,
    compute: computeFullCountSlg,
    formatValue: formatSlashStat,
  },
  {
    id: "full-count-ops",
    title: "Full Count OPS Merchants",
    subtitle: "On-base plus slugging in plate appearances that reached 3-2.",
    category: "drama",
    sort: "desc",
    unit: "OPS",
    formula: "OBP + SLG",
    minGames: 20,
    compute: computeFullCountOps,
    formatValue: formatSlashStat,
  },
  {
    id: "pitching-k-per-game",
    title: "Pitching K Factory",
    subtitle: "Strikeouts recorded by the pitching staff per game.",
    category: "defense",
    sort: "desc",
    unit: "K/G",
    formula: "pitching strikeouts ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.pitchingStrikeouts / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(1),
  },
  // —— Pace ——
  {
    id: "pitches-seen-per-half",
    title: "Pitches Seen Per Half",
    subtitle: "Average pitches the offense watches per half inning.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    formula: "pitches seen ÷ batting half innings",
    minGames: 20,
    compute: (c) =>
      c.battingHalfInnings > 0 ? c.pitchesSeen / c.battingHalfInnings : null,
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "pitches-thrown-per-half",
    title: "Pitches Thrown Per Half",
    subtitle: "Average pitches the staff throws per defensive half inning.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    formula: "pitches thrown ÷ pitching half innings",
    minGames: 20,
    compute: (c) =>
      c.pitchingHalfInnings > 0 ? c.pitchesThrown / c.pitchingHalfInnings : null,
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "pitches-per-pa",
    title: "Pitches Per Plate Appearance",
    subtitle: "How many pitches batters see before the PA ends.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    formula: "pitches seen ÷ plate appearances",
    minGames: 20,
    compute: (c) =>
      c.plateAppearances > 0 ? c.pitchesSeen / c.plateAppearances : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "total-pitches-seen",
    title: "Pitch Gluttons",
    subtitle: "Total pitches seen by the offense this season.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    compute: (c) => c.pitchesSeen,
    formatValue: formatCount,
  },
  {
    id: "ball-rate",
    title: "Ball Hawk Rate",
    subtitle: "Share of pitches taken for balls.",
    category: "pace",
    sort: "desc",
    unit: "%",
    formula: "balls taken ÷ pitches seen × 100",
    minGames: 20,
    compute: (c) => pct(c.pitchBalls, c.pitchesSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "quick-half-innings-seen",
    title: "Quick Half Innings",
    subtitle: "Batting halves finished in fewer than 10 pitches.",
    category: "pace",
    sort: "desc",
    unit: "halves",
    formula: "batting half innings with < 10 pitches seen",
    minGames: 20,
    compute: (c) => c.quickHalfInningsSeen,
    formatValue: formatCount,
  },
  {
    id: "quick-half-innings-thrown",
    title: "Quick Defensive Halves",
    subtitle: "Defensive halves wrapped up in fewer than 10 pitches.",
    category: "pace",
    sort: "desc",
    unit: "halves",
    formula: "pitching half innings with < 10 pitches thrown",
    minGames: 20,
    compute: (c) => c.quickHalfInningsThrown,
    formatValue: formatCount,
  },
  {
    id: "long-half-innings-seen",
    title: "Marathon Half Innings",
    subtitle: "Batting halves that required more than 30 pitches.",
    category: "pace",
    sort: "desc",
    unit: "halves",
    formula: "batting half innings with > 30 pitches seen",
    minGames: 20,
    compute: (c) => c.longHalfInningsSeen,
    formatValue: formatCount,
  },
  {
    id: "long-half-innings-thrown",
    title: "Marathon Defensive Halves",
    subtitle: "Defensive halves where the staff threw more than 30 pitches.",
    category: "pace",
    sort: "desc",
    unit: "halves",
    formula: "pitching half innings with > 30 pitches thrown",
    minGames: 20,
    compute: (c) => c.longHalfInningsThrown,
    formatValue: formatCount,
  },
  {
    id: "shortest-half-inning-pitches",
    title: "Shortest Half Inning",
    subtitle: "Fewest pitches seen in any single batting half.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "min pitches seen in a batting half inning",
    minGames: 20,
    compute: (c) => c.shortestHalfInningPitchesSeen,
    formatValue: (v) => v.toFixed(0),
  },
  {
    id: "longest-half-inning-pitches",
    title: "Longest Half Inning",
    subtitle: "Most pitches seen in any single batting half.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    formula: "max pitches seen in a batting half inning",
    minGames: 20,
    compute: (c) => c.longestHalfInningPitchesSeen,
    formatValue: (v) => v.toFixed(0),
  },
  {
    id: "shortest-half-inning-pitches-thrown",
    title: "Shortest Defensive Half",
    subtitle: "Fewest pitches thrown in any single defensive half.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "min pitches thrown in a pitching half inning",
    minGames: 20,
    compute: (c) => c.shortestHalfInningPitchesThrown,
    formatValue: (v) => v.toFixed(0),
  },
  {
    id: "longest-half-inning-pitches-thrown",
    title: "Longest Defensive Half",
    subtitle: "Most pitches thrown in any single defensive half.",
    category: "pace",
    sort: "desc",
    unit: "pitches",
    formula: "max pitches thrown in a pitching half inning",
    minGames: 20,
    compute: (c) => c.longestHalfInningPitchesThrown,
    formatValue: (v) => v.toFixed(0),
  },
  {
    id: "pitches-per-run",
    title: "Pitches Per Run",
    subtitle: "How many pitches the offense needs to score a run.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "pitches seen ÷ runs scored",
    minGames: 20,
    compute: (c) => rate(c.pitchesSeen, c.runsScored),
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "pitches-per-run-allowed",
    title: "Pitches Per Run Allowed",
    subtitle: "How many pitches the staff throws per run allowed.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "pitches thrown ÷ runs allowed",
    minGames: 20,
    compute: (c) => rate(c.pitchesThrown, c.runsAllowed),
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "pitches-per-hit",
    title: "Pitches Per Hit",
    subtitle: "How many pitches the offense sees per hit.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "pitches seen ÷ hits",
    minGames: 20,
    compute: (c) => rate(c.pitchesSeen, c.hits),
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "pitches-per-hit-allowed",
    title: "Pitches Per Hit Allowed",
    subtitle: "How many pitches the staff throws per hit allowed.",
    category: "pace",
    sort: "asc",
    unit: "pitches",
    formula: "pitches thrown ÷ hits allowed",
    minGames: 20,
    compute: (c) => rate(c.pitchesThrown, c.hitsAllowed),
    formatValue: (v) => v.toFixed(1),
  },
  // —— Pitch contact ——
  {
    id: "foul-ball-factory",
    title: "Foul Ball Factory",
    subtitle: "Total foul balls as the batting team.",
    category: "contact",
    sort: "desc",
    unit: "fouls",
    compute: (c) => c.foulBalls,
    formatValue: formatCount,
  },
  {
    id: "foul-rate",
    title: "Foul Ball Rate",
    subtitle: "Share of pitches fouled off.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "foul balls ÷ pitches seen × 100",
    minGames: 20,
    compute: (c) => pct(c.foulBalls, c.pitchesSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "pitch-bip-rate",
    title: "Pitch Contact Rate",
    subtitle: "Share of pitches put in play (not foul, ball, or whiff).",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "balls in play ÷ pitches seen × 100",
    minGames: 20,
    compute: (c) => pct(c.ballsInPlay, c.pitchesSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "swinging-strike-rate",
    title: "Whiff Per Pitch",
    subtitle: "Swinging strikes per pitch seen.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "swinging strikes ÷ pitches seen × 100",
    minGames: 20,
    compute: (c) => pct(c.swingingStrikes, c.pitchesSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "called-strike-rate",
    title: "Freeze Rate",
    subtitle: "Called strikes per pitch seen.",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "called strikes ÷ pitches seen × 100",
    minGames: 20,
    compute: (c) => pct(c.calledStrikes, c.pitchesSeen),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "fouls-induced-per-game",
    title: "Foul Ball Annoyers",
    subtitle: "Foul balls induced by the pitching staff per game.",
    category: "defense",
    sort: "desc",
    unit: "fouls/G",
    formula: "fouls induced ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.foulsInduced / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "balls-in-play-allowed-rate",
    title: "Contact Allowed Rate",
    subtitle: "Share of pitches the staff allows in play.",
    category: "defense",
    sort: "asc",
    unit: "%",
    formula: "balls in play allowed ÷ pitches thrown × 100",
    minGames: 20,
    compute: (c) => pct(c.ballsInPlayAllowed, c.pitchesThrown),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "hbp-rate",
    title: "HBP Rate",
    subtitle: "Hit-by-pitches per plate appearance.",
    category: "misfortune",
    sort: "desc",
    unit: "%",
    formula: "HBP ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) => pct(c.hbp, c.plateAppearances),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "contact-rate",
    title: "Ball-in-Play Rate",
    subtitle: "Plate appearances ending in contact (not K, BB, or HR).",
    category: "contact",
    sort: "desc",
    unit: "%",
    formula: "(PA − K − BB − HR) ÷ plate appearances × 100",
    minGames: 20,
    compute: (c) =>
      pct(
        c.plateAppearances - c.strikeouts - c.walks - c.homeRuns,
        c.plateAppearances,
      ),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "swinging-strikes-per-game",
    title: "Whiff Rate Per Game",
    subtitle: "Swinging strikes per game as the batting team.",
    category: "chaos",
    sort: "desc",
    unit: "whiffs/G",
    formula: "swinging strikes ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.swingingStrikes / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(1),
  },
  {
    id: "walks-per-game",
    title: "Walks Per Game",
    subtitle: "Free passes drawn per game.",
    category: "chaos",
    sort: "desc",
    unit: "BB/G",
    formula: "walks ÷ games with feed",
    minGames: 20,
    compute: (c) =>
      c.finalGamesWithFeed > 0 ? c.walks / c.finalGamesWithFeed : null,
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "back-to-back-hr-sequences",
    title: "Back-to-Back Sequences",
    subtitle: "Every consecutive homer pair (and beyond).",
    category: "vibes",
    sort: "desc",
    unit: "pairs",
    compute: (c) => c.backToBackHrSequences,
    formatValue: formatCount,
  },
  {
    id: "pinch-hit-homer-rate",
    title: "Pinch-Hit Dinger Rate",
    subtitle: "Pinch-hit home runs per pinch appearance.",
    category: "vibes",
    sort: "desc",
    unit: "%",
    formula: "pinch HRs ÷ pinch attempts × 100",
    minGames: 5,
    compute: (c) => pct(c.pinchHitHomeRuns, c.pinchHitAttempts),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "chaos-gift-runs-per-game",
    title: "Chaos Gift Runs",
    subtitle: "Runs scored on errors, balks, wild pitches, and passed balls per game.",
    category: "chaos",
    sort: "desc",
    unit: "R/G",
    formula: "(error + balk + WP + PB runs) ÷ games with feed",
    minGames: 20,
    compute: (c) => {
      if (c.finalGamesWithFeed <= 0) return null;
      const gifts =
        c.errorRunBenefits +
        c.balkBenefits +
        c.wildPitchBenefits +
        c.passedBallBenefits;
      return gifts / c.finalGamesWithFeed;
    },
    formatValue: (v) => v.toFixed(2),
  },
  {
    id: "blowout-win-share",
    title: "Blowout Win Share",
    subtitle: "Share of wins that were by 5+ runs.",
    category: "drama",
    sort: "desc",
    unit: "%",
    formula: "blowout wins ÷ total wins × 100",
    minGames: 10,
    compute: (c) => pct(c.blowoutWins, c.wins),
    formatValue: (v) => formatPercent(v),
  },
  {
    id: "walkless-offense-rate",
    title: "Walkless Offense Rate",
    subtitle: "Games where the team drew zero walks.",
    category: "chaos",
    sort: "desc",
    unit: "%",
    formula: "zero-walk games ÷ games with feed × 100",
    minGames: 20,
    compute: (c) => pct(c.zeroWalkGames, c.finalGamesWithFeed),
    formatValue: (v) => formatPercent(v),
  },
  ...CONTACT_QUALITY_NERD_STAT_DEFINITIONS,
  ...PITCH_TYPE_NERD_STAT_DEFINITIONS,
];

export function getNerdStatDefinition(statId: string): NerdStatDefinition | undefined {
  return NERD_STAT_DEFINITIONS.find((stat) => stat.id === statId);
}
